[{"url":"https://api.github.com/repos/owncloud/core/issues/comments/28280255","html_url":"https://github.com/owncloud/core/issues/5820#issuecomment-28280255","issue_url":"https://api.github.com/repos/owncloud/core/issues/5820","id":28280255,"user":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false},"created_at":"2013-11-12t09:46:53z","updated_at":"2013-11-12t09:46:53z","body":"@aerofel can you post the full bug template please? https://github.com/owncloud/core/blob/master/contributing.md"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/28285103","html_url":"https://github.com/owncloud/core/issues/5820#issuecomment-28285103","issue_url":"https://api.github.com/repos/owncloud/core/issues/5820","id":28285103,"user":{"login":"aerofel","id":5917929,"avatar_url":"https://gravatar.com/avatar/cdef53140d8bd2a7d17cf52334c991ec?d=https%3a%2f%2fidenticons.github.com%2f28780fbbd97ae8fb05741fd2ab09e819.png&r=x","gravatar_id":"cdef53140d8bd2a7d17cf52334c991ec","url":"https://api.github.com/users/aerofel","html_url":"https://github.com/aerofel","followers_url":"https://api.github.com/users/aerofel/followers","following_url":"https://api.github.com/users/aerofel/following{/other_user}","gists_url":"https://api.github.com/users/aerofel/gists{/gist_id}","starred_url":"https://api.github.com/users/aerofel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/aerofel/subscriptions","organizations_url":"https://api.github.com/users/aerofel/orgs","repos_url":"https://api.github.com/users/aerofel/repos","events_url":"https://api.github.com/users/aerofel/events{/privacy}","received_events_url":"https://api.github.com/users/aerofel/received_events","type":"user","site_admin":false},"created_at":"2013-11-12t11:08:15z","updated_at":"2013-11-12t11:08:15z","body":"### expected behaviour\r\ndownload shared file from a non ldap user\r\n\r\n### actual behaviour\r\nfile not found when trying to download\r\n\r\n### steps to reproduce\r\n1. fresh owncloud installation\r\n2. ldap users\r\n3. create an additional regular non-ldap account\r\n4. share a file from the non-ldap account to an ldap user. ex file vector.vuze\r\n5. try to catch that file under shared on the ldap user side\r\n\r\n### server configuration\r\noperating system: ubuntu 10.04\r\n\r\nweb server: apache 2.2.14\r\n\r\ndatabase: mysql 5.1.7.2\r\n\r\nphp version: 5.3.2\r\n\r\nowncloud version: 5.0.12\r\n\r\n### client configuration\r\nbrowser: safari/chrome/firefox\r\n\r\noperating system: max os x\r\n\r\n### logs\r\n#### web server error log\r\n```\r\nget /owncloud/remote.php/webdav/shared/vertor.vuze http/1.1\" 404 794\r\n```\r\n\r\n#### owncloud log (data/owncloud.log)\r\n```\r\nno error\r\n```\r\n\r\n#### browser log\r\n```\r\ncloud not found\r\nin os x client:\r\n11-12 12:04:21:833 sync is enabled - starting the polltimer again. \r\n11-12 12:04:21:833 starting event logging again in  2000  milliseconds \r\n11-12 12:04:21:834 oo folder slotsyncfinished: result:  3 \r\n11-12 12:04:21:834   ** error strings:  (\"file shared: error within the directory\", \"file shared/vertor.vuze: not found\", \"file shared/datasheet_polycom_soundstation_ip_7000.pdf: not found\") \r\n11-12 12:04:21:834     * owncloud csync thread finished with error \r\n11-12 12:04:21:835 folder in overallstatus message:  mirall::folder(0x10695f1d0)  with name  \"owncloud\" \r\n11-12 12:04:21:835 sync state changed for folder  \"owncloud\" :  \"error\" \r\n11-12 12:04:21:836 setting up host header:  \"privajet.net\" \r\n11-12 12:04:21:836 <===================================== sync finished for  \"owncloud\" \r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/28341774","html_url":"https://github.com/owncloud/core/issues/5820#issuecomment-28341774","issue_url":"https://api.github.com/repos/owncloud/core/issues/5820","id":28341774,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2013-11-12t22:46:58z","updated_at":"2013-11-12t22:46:58z","body":"i cannot reproduce it. could you please change the log level to debug and try again?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/28420737","html_url":"https://github.com/owncloud/core/issues/5820#issuecomment-28420737","issue_url":"https://api.github.com/repos/owncloud/core/issues/5820","id":28420737,"user":{"login":"aerofel","id":5917929,"avatar_url":"https://gravatar.com/avatar/cdef53140d8bd2a7d17cf52334c991ec?d=https%3a%2f%2fidenticons.github.com%2f28780fbbd97ae8fb05741fd2ab09e819.png&r=x","gravatar_id":"cdef53140d8bd2a7d17cf52334c991ec","url":"https://api.github.com/users/aerofel","html_url":"https://github.com/aerofel","followers_url":"https://api.github.com/users/aerofel/followers","following_url":"https://api.github.com/users/aerofel/following{/other_user}","gists_url":"https://api.github.com/users/aerofel/gists{/gist_id}","starred_url":"https://api.github.com/users/aerofel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/aerofel/subscriptions","organizations_url":"https://api.github.com/users/aerofel/orgs","repos_url":"https://api.github.com/users/aerofel/repos","events_url":"https://api.github.com/users/aerofel/events{/privacy}","received_events_url":"https://api.github.com/users/aerofel/received_events","type":"user","site_admin":false},"created_at":"2013-11-13t18:35:52z","updated_at":"2013-11-13t18:35:52z","body":"sorry but log level was already set to debug. when hitting the download button, i only get this:\r\n{\"app\":\"core\",\"message\":\"include path for class \\\"oca_firstrunwizard\\\\config\\\" starts with \\\"apps\\/\\\"\",\"level\":0,\"time\":\"2013-11-13t18:34:20+00:00\"}\r\n{\"app\":\"core\",\"message\":\"include path for class \\\"oca_firstrunwizard\\\\config\\\" starts with \\\"apps\\/\\\"\",\"level\":0,\"time\":\"2013-11-13t18:34:20+00:00\"}\r\n{\"app\":\"core\",\"message\":\"include path for class \\\"oca_firstrunwizard\\\\config\\\" starts with \\\"apps\\/\\\"\",\"level\":0,\"time\":\"2013-11-13t18:34:20+00:00\"}\r\n{\"app\":\"core\",\"message\":\"include path for class \\\"oca_firstrunwizard\\\\config\\\" starts with \\\"apps\\/\\\"\",\"level\":0,\"time\":\"2013-11-13t18:34:20+00:00\"}\r\n{\"app\":\"core\",\"message\":\"include path for class \\\"oca_firstrunwizard\\\\config\\\" starts with \\\"apps\\/\\\"\",\"level\":0,\"time\":\"2013-11-13t18:34:20+00:00\"}"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/28421389","html_url":"https://github.com/owncloud/core/issues/5820#issuecomment-28421389","issue_url":"https://api.github.com/repos/owncloud/core/issues/5820","id":28421389,"user":{"login":"blizzz","id":2184312,"avatar_url":"https://gravatar.com/avatar/1898b25a9cb3aa1a0f0febd1359910b9?d=https%3a%2f%2fidenticons.github.com%2fca03acec6deadf508b75eb0cf9ba036c.png&r=x","gravatar_id":"1898b25a9cb3aa1a0f0febd1359910b9","url":"https://api.github.com/users/blizzz","html_url":"https://github.com/blizzz","followers_url":"https://api.github.com/users/blizzz/followers","following_url":"https://api.github.com/users/blizzz/following{/other_user}","gists_url":"https://api.github.com/users/blizzz/gists{/gist_id}","starred_url":"https://api.github.com/users/blizzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blizzz/subscriptions","organizations_url":"https://api.github.com/users/blizzz/orgs","repos_url":"https://api.github.com/users/blizzz/repos","events_url":"https://api.github.com/users/blizzz/events{/privacy}","received_events_url":"https://api.github.com/users/blizzz/received_events","type":"user","site_admin":false},"created_at":"2013-11-13t18:44:07z","updated_at":"2013-11-13t18:44:07z","body":"could you please upgrade to 5.0.13 and try again? there were some fixes regarding sharing, maybe this one as well."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/28438803","html_url":"https://github.com/owncloud/core/issues/5820#issuecomment-28438803","issue_url":"https://api.github.com/repos/owncloud/core/issues/5820","id":28438803,"user":{"login":"aerofel","id":5917929,"avatar_url":"https://gravatar.com/avatar/cdef53140d8bd2a7d17cf52334c991ec?d=https%3a%2f%2fidenticons.github.com%2f28780fbbd97ae8fb05741fd2ab09e819.png&r=x","gravatar_id":"cdef53140d8bd2a7d17cf52334c991ec","url":"https://api.github.com/users/aerofel","html_url":"https://github.com/aerofel","followers_url":"https://api.github.com/users/aerofel/followers","following_url":"https://api.github.com/users/aerofel/following{/other_user}","gists_url":"https://api.github.com/users/aerofel/gists{/gist_id}","starred_url":"https://api.github.com/users/aerofel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/aerofel/subscriptions","organizations_url":"https://api.github.com/users/aerofel/orgs","repos_url":"https://api.github.com/users/aerofel/repos","events_url":"https://api.github.com/users/aerofel/events{/privacy}","received_events_url":"https://api.github.com/users/aerofel/received_events","type":"user","site_admin":false},"created_at":"2013-11-13t22:06:48z","updated_at":"2013-11-13t22:06:48z","body":"just reinstalled with 5.0.13, and now, no more issue. thanks a lot for your help, all this looks very promising!\r\n\r\n"}]