[{"url":"https://api.github.com/repos/owncloud/core/issues/comments/25071817","html_url":"https://github.com/owncloud/core/issues/4984#issuecomment-25071817","issue_url":"https://api.github.com/repos/owncloud/core/issues/4984","id":25071817,"user":{"login":"deepdiver1975","id":1005065,"avatar_url":"https://gravatar.com/avatar/bdba071ed68da9ce8edae53c364902ef?d=https%3a%2f%2fidenticons.github.com%2f67e101ad9531b7d25697b76e503e062e.png&r=x","gravatar_id":"bdba071ed68da9ce8edae53c364902ef","url":"https://api.github.com/users/deepdiver1975","html_url":"https://github.com/deepdiver1975","followers_url":"https://api.github.com/users/deepdiver1975/followers","following_url":"https://api.github.com/users/deepdiver1975/following{/other_user}","gists_url":"https://api.github.com/users/deepdiver1975/gists{/gist_id}","starred_url":"https://api.github.com/users/deepdiver1975/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/deepdiver1975/subscriptions","organizations_url":"https://api.github.com/users/deepdiver1975/orgs","repos_url":"https://api.github.com/users/deepdiver1975/repos","events_url":"https://api.github.com/users/deepdiver1975/events{/privacy}","received_events_url":"https://api.github.com/users/deepdiver1975/received_events","type":"user","site_admin":false},"created_at":"2013-09-25t09:09:16z","updated_at":"2013-09-25t09:09:16z","body":"@schiesbn @ringmaster thx"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/25077035","html_url":"https://github.com/owncloud/core/issues/4984#issuecomment-25077035","issue_url":"https://api.github.com/repos/owncloud/core/issues/4984","id":25077035,"user":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false},"created_at":"2013-09-25t10:49:57z","updated_at":"2013-09-25t10:52:19z","body":"it looks like the user \"\"a8928d60-789f-44bc-afcd-2ba8405beecf\" doesn't have a key-pair yet. every user needs to log-in at least once after the encryption app was enabled.\r\n\r\nif you share the file after the encryption app was enabled owncloud should detect that not all users are ready and prompt an error message in the web interface. if the file was already shared before, that there is nothing we can do about it.\r\n\r\ncan you try it once more after all users from the group logged-in at least once, to make sure that it is not a general problem but the problem i described above?\r\n\r\nif you were able to share to the group without getting a error message,  even if not everyone has a key-pair than this is probably a windows-only issue... @ringmaster would be great if you could have a look at it. "},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/25078820","html_url":"https://github.com/owncloud/core/issues/4984#issuecomment-25078820","issue_url":"https://api.github.com/repos/owncloud/core/issues/4984","id":25078820,"user":{"login":"salva86","id":5435795,"avatar_url":"https://gravatar.com/avatar/f6853cda910972edf75dc1dc6f423831?d=https%3a%2f%2fidenticons.github.com%2fa35e03ca04197309f20ae872a8b53f16.png&r=x","gravatar_id":"f6853cda910972edf75dc1dc6f423831","url":"https://api.github.com/users/salva86","html_url":"https://github.com/salva86","followers_url":"https://api.github.com/users/salva86/followers","following_url":"https://api.github.com/users/salva86/following{/other_user}","gists_url":"https://api.github.com/users/salva86/gists{/gist_id}","starred_url":"https://api.github.com/users/salva86/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/salva86/subscriptions","organizations_url":"https://api.github.com/users/salva86/orgs","repos_url":"https://api.github.com/users/salva86/repos","events_url":"https://api.github.com/users/salva86/events{/privacy}","received_events_url":"https://api.github.com/users/salva86/received_events","type":"user","site_admin":false},"created_at":"2013-09-25t11:29:19z","updated_at":"2013-09-25t11:35:53z","body":"i have tried logging the user in and out again. i have created a new user didnt work also. sharing works i can see the files, but like i said, they are encrypted (new files and old files). the files from \"a8928d60-789f-44bc-afcd-2ba8405beecf\" are encrypted and everything works - just the shared ones dont... \r\n\r\nevery user has to be logged in and out? when i check my database i have old guids from old ldap users. the database doesnt delete these. do i have to delete these manually? maybe the encryption app \"waits\" until these users are logged in??? the users arent unter \"users\" in the owncloud web interface or in the active directory group!\r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/26981717","html_url":"https://github.com/owncloud/core/issues/4984#issuecomment-26981717","issue_url":"https://api.github.com/repos/owncloud/core/issues/4984","id":26981717,"user":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false},"created_at":"2013-10-24t10:33:36z","updated_at":"2013-10-24t10:33:36z","body":"@schiesbn is this still open?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/26987458","html_url":"https://github.com/owncloud/core/issues/4984#issuecomment-26987458","issue_url":"https://api.github.com/repos/owncloud/core/issues/4984","id":26987458,"user":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false},"created_at":"2013-10-24t12:23:32z","updated_at":"2013-10-24t12:23:32z","body":"i can't reproduce it and the error message is quite clear (\"a8928d60-789f-44bc-afcd-2ba8405beecf\" is not setup for encryption). if the user isn't set-up for encryption than the file can't be encrypted/decrypted to him.\r\n\r\nsolution: \r\n- make sure that the user is set-up correctly: log-in as the user\r\n- than unshare the file and share it again"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/26988121","html_url":"https://github.com/owncloud/core/issues/4984#issuecomment-26988121","issue_url":"https://api.github.com/repos/owncloud/core/issues/4984","id":26988121,"user":{"login":"ringmaster","id":127738,"avatar_url":"https://gravatar.com/avatar/2e4c262dd7f74a26b28f905c0fa15048?d=https%3a%2f%2fidenticons.github.com%2f968ec2eda9ddfebb1b5a00c05b9cc674.png&r=x","gravatar_id":"2e4c262dd7f74a26b28f905c0fa15048","url":"https://api.github.com/users/ringmaster","html_url":"https://github.com/ringmaster","followers_url":"https://api.github.com/users/ringmaster/followers","following_url":"https://api.github.com/users/ringmaster/following{/other_user}","gists_url":"https://api.github.com/users/ringmaster/gists{/gist_id}","starred_url":"https://api.github.com/users/ringmaster/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ringmaster/subscriptions","organizations_url":"https://api.github.com/users/ringmaster/orgs","repos_url":"https://api.github.com/users/ringmaster/repos","events_url":"https://api.github.com/users/ringmaster/events{/privacy}","received_events_url":"https://api.github.com/users/ringmaster/received_events","type":"user","site_admin":false},"created_at":"2013-10-24t12:34:33z","updated_at":"2013-10-24t12:34:33z","body":"the test for this is still failing under windows.  i don't know yet if it's because of the test (incorrectly setting up encryption for a user) or because of the code.  though if it's not possible to reproduce manually, i suspect the test is simply fragile.  there seem to be some instances in the tests where simple things can cause exceptions that halt the test but leave it in an inconsistent state that ruins subsequent tests.  not sure if/how that affects jenkins, but for repeated local testing, it's extremely bothersome.  regardless, the test for this still fails under windows and is something i've been looking into (among other windows encryption test failures) for the past couple days."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/26988936","html_url":"https://github.com/owncloud/core/issues/4984#issuecomment-26988936","issue_url":"https://api.github.com/repos/owncloud/core/issues/4984","id":26988936,"user":{"login":"deepdiver1975","id":1005065,"avatar_url":"https://gravatar.com/avatar/bdba071ed68da9ce8edae53c364902ef?d=https%3a%2f%2fidenticons.github.com%2f67e101ad9531b7d25697b76e503e062e.png&r=x","gravatar_id":"bdba071ed68da9ce8edae53c364902ef","url":"https://api.github.com/users/deepdiver1975","html_url":"https://github.com/deepdiver1975","followers_url":"https://api.github.com/users/deepdiver1975/followers","following_url":"https://api.github.com/users/deepdiver1975/following{/other_user}","gists_url":"https://api.github.com/users/deepdiver1975/gists{/gist_id}","starred_url":"https://api.github.com/users/deepdiver1975/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/deepdiver1975/subscriptions","organizations_url":"https://api.github.com/users/deepdiver1975/orgs","repos_url":"https://api.github.com/users/deepdiver1975/repos","events_url":"https://api.github.com/users/deepdiver1975/events{/privacy}","received_events_url":"https://api.github.com/users/deepdiver1975/received_events","type":"user","site_admin":false},"created_at":"2013-10-24t12:47:38z","updated_at":"2013-10-24t12:47:38z","body":"@karlitschek @ringmaster @schiesbn as long as we are still facing generall issues with encryption on linux backends it might be a valid approach to not allow encryption on windows servers for oc6 - objections?\r\n\r\nthat could be a time saver for the oc6 release"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/26990587","html_url":"https://github.com/owncloud/core/issues/4984#issuecomment-26990587","issue_url":"https://api.github.com/repos/owncloud/core/issues/4984","id":26990587,"user":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false},"created_at":"2013-10-24t13:12:20z","updated_at":"2013-10-24t13:12:20z","body":"actually we have to fix it. sorry. @ringmaster can you help please?"}]