[{"url":"https://api.github.com/repos/owncloud/core/issues/comments/15188044","html_url":"https://github.com/owncloud/core/issues/759#issuecomment-15188044","issue_url":"https://api.github.com/repos/owncloud/core/issues/759","id":15188044,"user":{"login":"jancborchardt","id":925062,"avatar_url":"https://gravatar.com/avatar/2fd3f4d5d762955e5b603794a888fa97?d=https%3a%2f%2fidenticons.github.com%2f84ec51f9ceed468217d4e13abf78da9c.png&r=x","gravatar_id":"2fd3f4d5d762955e5b603794a888fa97","url":"https://api.github.com/users/jancborchardt","html_url":"https://github.com/jancborchardt","followers_url":"https://api.github.com/users/jancborchardt/followers","following_url":"https://api.github.com/users/jancborchardt/following{/other_user}","gists_url":"https://api.github.com/users/jancborchardt/gists{/gist_id}","starred_url":"https://api.github.com/users/jancborchardt/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jancborchardt/subscriptions","organizations_url":"https://api.github.com/users/jancborchardt/orgs","repos_url":"https://api.github.com/users/jancborchardt/repos","events_url":"https://api.github.com/users/jancborchardt/events{/privacy}","received_events_url":"https://api.github.com/users/jancborchardt/received_events","type":"user","site_admin":false},"created_at":"2013-03-20t16:49:25z","updated_at":"2013-03-20t16:49:25z","body":"@deepdiver1975 any update on this?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/16241251","html_url":"https://github.com/owncloud/core/issues/759#issuecomment-16241251","issue_url":"https://api.github.com/repos/owncloud/core/issues/759","id":16241251,"user":{"login":"lozair31","id":3875494,"avatar_url":"https://gravatar.com/avatar/2b8d2a4607f2e6190d005414dab6ed5a?d=https%3a%2f%2fidenticons.github.com%2f3cf5322245979cfa240c428dde843b3a.png&r=x","gravatar_id":"2b8d2a4607f2e6190d005414dab6ed5a","url":"https://api.github.com/users/lozair31","html_url":"https://github.com/lozair31","followers_url":"https://api.github.com/users/lozair31/followers","following_url":"https://api.github.com/users/lozair31/following{/other_user}","gists_url":"https://api.github.com/users/lozair31/gists{/gist_id}","starred_url":"https://api.github.com/users/lozair31/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lozair31/subscriptions","organizations_url":"https://api.github.com/users/lozair31/orgs","repos_url":"https://api.github.com/users/lozair31/repos","events_url":"https://api.github.com/users/lozair31/events{/privacy}","received_events_url":"https://api.github.com/users/lozair31/received_events","type":"user","site_admin":false},"created_at":"2013-04-11t15:20:07z","updated_at":"2013-04-11t15:20:07z","body":"hi we encountered a similar or linked problem.\r\n\r\nour env is : \r\n**************\r\nenvironment: virtual centos 6.3 linux server\r\nserver: apache\r\ndatabase: mysql\r\nclient: android 1.3.22 apps, ipad last appstore version and firefox for web client\r\noc-version: 5.0.3\r\nphp-version: php-5.3.3-22.el6\r\n\r\n\r\nsummary : \r\n*************\r\nwe use oc to access smb share on our emc nas.\r\nwe use the last oc5 feature to allow each user to mount our homedir via the external_storage gui.\r\n\r\nall work fine, a user can declare a share in the oc gui.\r\nhe can parse the share (his homedir) using the oc5 web gui and he can upload files to this share from the web interface.\r\n\r\nwe want to deploy android and ios apps to our users and webdav clients on our computers.\r\n\r\non all the devices the user can access his smb share and download files.\r\nthe problem arise when the user want upload a file inside the share from his mobile device.\r\nthe upload operation is not successfull.\r\n\r\non android mobile device the upload seems blocked to 0%.\r\non the oc gui we can see a growing number of files with 0bytes size appearing.\r\nthe only solution to stop this generation is to restart the apache server.\r\non the smb share these files never exists.\r\n\r\non webdav computer client we got a \"file already exists in destination\".\r\nif we force the upload, the file is uploaded correctly\r\n\r\non ios device, we can only upload photos shared from ios, the upload works great.....\r\n\r\n\r\ndetailed informations : \r\n**************************\r\n\r\nlooking the owncloud app log file on our server we have the following logs : \r\n\r\n{\"app\":\"php\",\"message\":\"stat(): stat failed for smb:\\/\\/user:password@server\\share\\testfile.doc at \\/var\\/www\\/html\\/owncloud\\/apps\\/files_external\\/lib\\/smb.php#65\",\"level\":2,\"time\":1365676049}\r\n{\"app\":\"php\",\"message\":\"filetype(): lstat failed for smb:\\/\\/user:password@server\\share\\testfile.doc at \\/var\\/www\\/html\\/owncloud\\/apps\\/files_external\\/lib\\/streamwrapper.php#51\",\"level\":2,\"time\":1365676049}\r\n\r\nbut it seems this error message is not the source problem.\r\n\r\nindeed reading apache logs produced when attemting to upload a  file from our android device we can see : \r\n\r\n x.x.x.x - user [11/apr/2013:15:08:19 +02] \"head /remote.php/webdav/sharename/file.jpg http/1.1\" 200 - \"-\" \"android-owncloud\"\r\nx.x.x.x - user [11/apr/2013:15:08:20 +02] \"head /remote.php/webdav/sharename/file.jpg http/1.1\" 200 - \"-\" \"android-owncloud\"\r\n......\r\n......\r\nuntil we restart the oc apache server.\r\n\r\n\r\nfrom the computer nautilus webdav client whe have the following logs when we force the write : \r\n\r\nx.x.x.x - user [11/apr/2013:16:57:19 +0200] \"head /files/webdav.php/sharename/file.png http/1.1\" 200 - \"-\" \"gvfs/1.6.4\"\r\nx.x.x.x - user [11/apr/2013:16:57:20 +0200] \"propfind /files/webdav.php/sharename/file.png http/1.1\" 207 526 \"-\" \"gvfs/1.6.4\"\r\nx.x.x.x - user [11/apr/2013:16:57:20 +0200] \"propfind /files/webdav.php/sharename/file.png http/1.1\" 207 526 \"-\" \"gvfs/1.6.4\"\r\nx.x.x.x - user [11/apr/2013:16:57:27 +0200] \"put /files/webdav.php/sharename/file.png http/1.1\" 201 - \"-\" \"gvfs/1.6.4\"\r\n\r\n\r\nfrom the ios client we have the following logs (all work fine with this device...): \r\n\r\nx.x.x.x - username [11/apr/2013:17:03:47 +0200] \"propfind /remote.php/webdav/sharename/file.jpg http/1.1\" 207 341 \"-\" \"owncloud%20ios%20client/2.09 cfnetwork/609.1.4 darwin/13.0.0\"\r\nx.x.x.x - username [11/apr/2013:17:03:47 +0200] \"put /remote.php/webdav/sharename/file.jpg http/1.1\" 201 - \"-\" \"owncloud%20ios%20client/2.09 cfnetwork/609.1.4 darwin/13.0.0\"\r\n\r\n\r\nso it seems different clients use diffferent http/webdav methods to test file exists on the oc instance.\r\nit's perhaps the problem source ......\r\n\r\n\r\ni can confirm the upload on the local oc filesysteme doesn't make problem from any device.\r\nthe logs we can see when we upload on the local oc filesystem follows : \r\n\r\n \r\nx.x.x.x - username [11/apr/2013:17:13:04 +0200] \"propfind /files/webdav.php/local http/1.1\" 207 574 \"-\" \"gvfs/1.6.4\"\r\nx.x.x.x - username [11/apr/2013:17:13:04 +0200] \"head /files/webdav.php/local/file2.png http/1.1\" 404 - \"-\" \"gvfs/1.6.4\"\r\nx.x.x.x - username [11/apr/2013:17:13:05 +0200] \"put /files/webdav.php/local/file2.png http/1.1\" 201 - \r\n\r\n\r\nhere we can see the 404 response which seems to show the file doesn't exists in destination...\r\n\r\nanyone encounter the same problem ?\r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/22110102","html_url":"https://github.com/owncloud/core/issues/759#issuecomment-22110102","issue_url":"https://api.github.com/repos/owncloud/core/issues/759","id":22110102,"user":{"login":"jancborchardt","id":925062,"avatar_url":"https://gravatar.com/avatar/2fd3f4d5d762955e5b603794a888fa97?d=https%3a%2f%2fidenticons.github.com%2f84ec51f9ceed468217d4e13abf78da9c.png&r=x","gravatar_id":"2fd3f4d5d762955e5b603794a888fa97","url":"https://api.github.com/users/jancborchardt","html_url":"https://github.com/jancborchardt","followers_url":"https://api.github.com/users/jancborchardt/followers","following_url":"https://api.github.com/users/jancborchardt/following{/other_user}","gists_url":"https://api.github.com/users/jancborchardt/gists{/gist_id}","starred_url":"https://api.github.com/users/jancborchardt/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jancborchardt/subscriptions","organizations_url":"https://api.github.com/users/jancborchardt/orgs","repos_url":"https://api.github.com/users/jancborchardt/repos","events_url":"https://api.github.com/users/jancborchardt/events{/privacy}","received_events_url":"https://api.github.com/users/jancborchardt/received_events","type":"user","site_admin":false},"created_at":"2013-08-05t14:35:49z","updated_at":"2013-08-05t14:35:49z","body":"i’m closing this issue because it has been inactive for a few months. this probably means it’s not reproducible or it has been fixed in a newer version.\r\n\r\nplease reopen if the error still persists with the [latest stable version](http://owncloud.org/install/) (currently owncloud 5.0.9) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). you an also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)\r\n\r\nthank you!"}]