[{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21054313","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21054313","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21054313,"user":{"login":"realrancor","id":2248459,"avatar_url":"https://gravatar.com/avatar/f6105e79dfcfb0fcbabb3db061135c08?d=https%3a%2f%2fidenticons.github.com%2f7a70061016eba74d85c060de0f65212d.png&r=x","gravatar_id":"f6105e79dfcfb0fcbabb3db061135c08","url":"https://api.github.com/users/realrancor","html_url":"https://github.com/realrancor","followers_url":"https://api.github.com/users/realrancor/followers","following_url":"https://api.github.com/users/realrancor/following{/other_user}","gists_url":"https://api.github.com/users/realrancor/gists{/gist_id}","starred_url":"https://api.github.com/users/realrancor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/realrancor/subscriptions","organizations_url":"https://api.github.com/users/realrancor/orgs","repos_url":"https://api.github.com/users/realrancor/repos","events_url":"https://api.github.com/users/realrancor/events{/privacy}","received_events_url":"https://api.github.com/users/realrancor/received_events","type":"user","site_admin":false},"created_at":"2013-07-16t16:27:05z","updated_at":"2013-07-16t16:27:05z","body":"hi,\r\n\r\nthe exactly same mysql error was also posted one issue below your's: https://github.com/owncloud/core/issues/4084"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21054521","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21054521","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21054521,"user":{"login":"kondou-ger","id":1410802,"avatar_url":"https://gravatar.com/avatar/917dab919ae812f8252b2f501c514b19?d=https%3a%2f%2fidenticons.github.com%2fd07869ed62cb1b7f88b731956ab913ee.png&r=x","gravatar_id":"917dab919ae812f8252b2f501c514b19","url":"https://api.github.com/users/kondou-ger","html_url":"https://github.com/kondou-ger","followers_url":"https://api.github.com/users/kondou-ger/followers","following_url":"https://api.github.com/users/kondou-ger/following{/other_user}","gists_url":"https://api.github.com/users/kondou-ger/gists{/gist_id}","starred_url":"https://api.github.com/users/kondou-ger/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kondou-ger/subscriptions","organizations_url":"https://api.github.com/users/kondou-ger/orgs","repos_url":"https://api.github.com/users/kondou-ger/repos","events_url":"https://api.github.com/users/kondou-ger/events{/privacy}","received_events_url":"https://api.github.com/users/kondou-ger/received_events","type":"user","site_admin":false},"created_at":"2013-07-16t16:29:47z","updated_at":"2013-07-16t16:30:30z","body":"@realrancor it's not exactly the same issue though â€¦ #4084 is 5.0.8->5.0.9.\r\nthis is 5.0.7->5.0.8.\r\n\r\nthe error message is the same though."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21055021","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21055021","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21055021,"user":{"login":"realrancor","id":2248459,"avatar_url":"https://gravatar.com/avatar/f6105e79dfcfb0fcbabb3db061135c08?d=https%3a%2f%2fidenticons.github.com%2f7a70061016eba74d85c060de0f65212d.png&r=x","gravatar_id":"f6105e79dfcfb0fcbabb3db061135c08","url":"https://api.github.com/users/realrancor","html_url":"https://github.com/realrancor","followers_url":"https://api.github.com/users/realrancor/followers","following_url":"https://api.github.com/users/realrancor/following{/other_user}","gists_url":"https://api.github.com/users/realrancor/gists{/gist_id}","starred_url":"https://api.github.com/users/realrancor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/realrancor/subscriptions","organizations_url":"https://api.github.com/users/realrancor/orgs","repos_url":"https://api.github.com/users/realrancor/repos","events_url":"https://api.github.com/users/realrancor/events{/privacy}","received_events_url":"https://api.github.com/users/realrancor/received_events","type":"user","site_admin":false},"created_at":"2013-07-16t16:37:12z","updated_at":"2013-07-16t16:37:12z","body":"@kondou-ger \r\n\r\nsure, i just was talking about the same mysql error. :-)"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21057615","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21057615","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21057615,"user":{"login":"valleygeek","id":5023191,"avatar_url":"https://gravatar.com/avatar/cc4caf88c02c37a391cf31ac66c72a22?d=https%3a%2f%2fidenticons.github.com%2fdc47389544535b41a12decad5216d019.png&r=x","gravatar_id":"cc4caf88c02c37a391cf31ac66c72a22","url":"https://api.github.com/users/valleygeek","html_url":"https://github.com/valleygeek","followers_url":"https://api.github.com/users/valleygeek/followers","following_url":"https://api.github.com/users/valleygeek/following{/other_user}","gists_url":"https://api.github.com/users/valleygeek/gists{/gist_id}","starred_url":"https://api.github.com/users/valleygeek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/valleygeek/subscriptions","organizations_url":"https://api.github.com/users/valleygeek/orgs","repos_url":"https://api.github.com/users/valleygeek/repos","events_url":"https://api.github.com/users/valleygeek/events{/privacy}","received_events_url":"https://api.github.com/users/valleygeek/received_events","type":"user","site_admin":false},"created_at":"2013-07-16t17:15:27z","updated_at":"2013-07-16t17:15:27z","body":"ha, well i sure feel blind now, they are indeed the same error. although i can see an argument for the version making them two separate issues. if it is decided to merge them, i have no issues with that. in any case, any advice is appreciated. i thought i should report it here before i begin hacking at it."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21093058","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21093058","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21093058,"user":{"login":"realrancor","id":2248459,"avatar_url":"https://gravatar.com/avatar/f6105e79dfcfb0fcbabb3db061135c08?d=https%3a%2f%2fidenticons.github.com%2f7a70061016eba74d85c060de0f65212d.png&r=x","gravatar_id":"f6105e79dfcfb0fcbabb3db061135c08","url":"https://api.github.com/users/realrancor","html_url":"https://github.com/realrancor","followers_url":"https://api.github.com/users/realrancor/followers","following_url":"https://api.github.com/users/realrancor/following{/other_user}","gists_url":"https://api.github.com/users/realrancor/gists{/gist_id}","starred_url":"https://api.github.com/users/realrancor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/realrancor/subscriptions","organizations_url":"https://api.github.com/users/realrancor/orgs","repos_url":"https://api.github.com/users/realrancor/repos","events_url":"https://api.github.com/users/realrancor/events{/privacy}","received_events_url":"https://api.github.com/users/realrancor/received_events","type":"user","site_admin":false},"created_at":"2013-07-17t05:32:29z","updated_at":"2013-07-17t05:32:29z","body":"ah, and just noted that you're also getting the failed query to rename the calendar table. some infos about this can be found here: https://github.com/owncloud/core/issues/4013"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21095782","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21095782","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21095782,"user":{"login":"valleygeek","id":5023191,"avatar_url":"https://gravatar.com/avatar/cc4caf88c02c37a391cf31ac66c72a22?d=https%3a%2f%2fidenticons.github.com%2fdc47389544535b41a12decad5216d019.png&r=x","gravatar_id":"cc4caf88c02c37a391cf31ac66c72a22","url":"https://api.github.com/users/valleygeek","html_url":"https://github.com/valleygeek","followers_url":"https://api.github.com/users/valleygeek/followers","following_url":"https://api.github.com/users/valleygeek/following{/other_user}","gists_url":"https://api.github.com/users/valleygeek/gists{/gist_id}","starred_url":"https://api.github.com/users/valleygeek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/valleygeek/subscriptions","organizations_url":"https://api.github.com/users/valleygeek/orgs","repos_url":"https://api.github.com/users/valleygeek/repos","events_url":"https://api.github.com/users/valleygeek/events{/privacy}","received_events_url":"https://api.github.com/users/valleygeek/received_events","type":"user","site_admin":false},"created_at":"2013-07-17t07:12:09z","updated_at":"2013-07-17t07:12:09z","body":"@realrancor thanks for the followup on the calendar. i took the steps outlined by @georgehrke https://github.com/owncloud/core/issues/4013#issuecomment-20775533\r\n\r\nupon refresh of my installation i am presented with the same ui output as pictured in my op but my owncloud.log output is shorter as follows:\r\n```\r\n{\"app\":\"core\",\"message\":\"adding user backend instance of oc_user_database.\",\"level\":0,\"time\":1374044147}\r\n{\"app\":\"core\",\"message\":\"adding user backend instance of oc_user_database.\",\"level\":0,\"time\":1374044147}\r\n{\"app\":\"core\",\"message\":\"adding user backend instance of oc_user_database.\",\"level\":0,\"time\":1374044147}\r\n{\"app\":\"core\",\"message\":\"starting upgrade from 5.0.12 to 5.0.14\",\"level\":2,\"time\":1374044147}\r\n{\"app\":\"core\",\"message\":\"failed to update database structure (mdb2 error: unknown error, _doquery: [error message: could not execute statement]\\n[last executed query: alter table `oc_locks` change `id` `id` int unsigned not null auto_increment primary key, change `timeout` `timeout` int unsigned default 0, change `created` `created` bigint default 0, change `scope` `scope` tinyint default 0, change `depth` `depth` tinyint default 0]\\n[native code: 1068]\\n[native message: multiple primary key defined]\\n)\",\"level\":4,\"time\":1374044148}\r\n{\"app\":\"core\",\"message\":\"adding user backend instance of oc_user_database.\",\"level\":0,\"time\":1374044148}\r\n{\"app\":\"core\",\"message\":\"adding user backend instance of oc_user_database.\",\"level\":0,\"time\":1374044148}\r\n```\r\n\r\nfor reference, here is the schema for my oc_locks table:\r\n```mysql\r\nmysql> describe oc_locks;\r\n+---------+------------------+------+-----+---------+----------------+\r\n| field   | type             | null | key | default | extra          |\r\n+---------+------------------+------+-----+---------+----------------+\r\n| id      | int(11)          | no   | pri | null    | auto_increment |\r\n| userid  | varchar(64)      | yes  |     | null    |                |\r\n| owner   | varchar(100)     | yes  |     | null    |                |\r\n| timeout | int(10) unsigned | yes  |     | 0       |                |\r\n| created | bigint(20)       | yes  |     | 0       |                |\r\n| token   | varchar(100)     | yes  |     | null    |                |\r\n| scope   | smallint(6)      | yes  |     | 0       |                |\r\n| depth   | smallint(6)      | yes  |     | 0       |                |\r\n| uri     | longtext         | yes  |     | null    |                |\r\n+---------+------------------+------+-----+---------+----------------+\r\n9 rows in set (0.00 sec)\r\n```\r\n\r\ni am happy to try and test any suggestions or provide further information as able. i would like to get my installation back up soon, but i don't have an urgent need.\r\n\r\non a semi-related note, i notice that i now have apache and php updates available. i have not installed them yet so that my environment would be consistent for troubleshooting. however, i can and will install them if asked to.\r\n```\r\nthe following packages will be upgraded:\r\n  apache2 apache2-mpm-prefork apache2-utils apache2.2-bin apache2.2-common libapache2-mod-php5 libxml2 libxml2-utils php-pear php5 php5-cli php5-common php5-curl php5-gd php5-intl php5-mysql php5-sqlite\r\n```"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21130245","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21130245","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21130245,"user":{"login":"ghost","id":10137,"avatar_url":"https://gravatar.com/avatar/ac0c4949f8df628b3f77a42a3b814c4d?d=https%3a%2f%2fidenticons.github.com%2f715e8ba46f8bc29c24f3fbfdb8d96d71.png&r=x","gravatar_id":"ac0c4949f8df628b3f77a42a3b814c4d","url":"https://api.github.com/users/ghost","html_url":"https://github.com/ghost","followers_url":"https://api.github.com/users/ghost/followers","following_url":"https://api.github.com/users/ghost/following{/other_user}","gists_url":"https://api.github.com/users/ghost/gists{/gist_id}","starred_url":"https://api.github.com/users/ghost/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ghost/subscriptions","organizations_url":"https://api.github.com/users/ghost/orgs","repos_url":"https://api.github.com/users/ghost/repos","events_url":"https://api.github.com/users/ghost/events{/privacy}","received_events_url":"https://api.github.com/users/ghost/received_events","type":"user","site_admin":false},"created_at":"2013-07-17t17:39:51z","updated_at":"2013-07-17t17:39:51z","body":"i'm having trouble updating from 5.0.7 to 5.0.9 as well...\r\n\r\n\tupdating owncloud to version 5.0.9, this may take a while.\r\n\t\r\n\tturned on maintenance mode\r\n\tfailed to update database structure (mdb2 error: already exists, _doquery: [error message: could not execute statement] [last executed query: create table \"oc_filecache\" (\"fileid\" integer primary key autoincrement, \"storage\" integer default 0 not null, \"path\" varchar(512), \"path_hash\" varchar(32) default ' ' not null, \"parent\" integer default 0 not null, \"name\" varchar(250), \"mimetype\" integer default 0 not null, \"mimepart\" integer default 0 not null, \"size\" bigint default 0 not null, \"mtime\" integer default 0 not null, \"encrypted\" integer default 0 not null, \"etag\" varchar(40) default ' ' not null, \"unencrypted_size\" bigint default 0 not null)] [native code: 1] [native message: table \"oc_filecache\" already exists] )\r\n\t\r\n\tthe update was unsuccessful. please report this issue to the owncloud community."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21315010","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21315010","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21315010,"user":{"login":"brotkastn","id":604466,"avatar_url":"https://gravatar.com/avatar/4df8961b07bfc513f454f82a6d9bd21c?d=https%3a%2f%2fidenticons.github.com%2f9da986bb5f8b2429ae26abf0b53de926.png&r=x","gravatar_id":"4df8961b07bfc513f454f82a6d9bd21c","url":"https://api.github.com/users/brotkastn","html_url":"https://github.com/brotkastn","followers_url":"https://api.github.com/users/brotkastn/followers","following_url":"https://api.github.com/users/brotkastn/following{/other_user}","gists_url":"https://api.github.com/users/brotkastn/gists{/gist_id}","starred_url":"https://api.github.com/users/brotkastn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/brotkastn/subscriptions","organizations_url":"https://api.github.com/users/brotkastn/orgs","repos_url":"https://api.github.com/users/brotkastn/repos","events_url":"https://api.github.com/users/brotkastn/events{/privacy}","received_events_url":"https://api.github.com/users/brotkastn/received_events","type":"user","site_admin":false},"created_at":"2013-07-21t19:07:42z","updated_at":"2013-07-21t19:07:42z","body":"i can confirm problems with the upgrade to 5.0.9, this is what i am getting:\r\n<code>{\"app\":\"core\",\"message\":\"starting upgrade from 5.0.12 to 5.0.15\",\"level\":2,\"time\":1374433237}\r\n{\"app\":\"core\",\"message\":\"failed to update database structure (mdb2 error: unknown error, _doquery: [error message: could not execute statement]\\n[last executed query: alter table `oc_locks` change `id` `id` int unsigned not null auto_increment primary key, change `timeout` `timeout` int unsigned default 0, change `created` `created` bigint default 0, change `scope` `scope` tinyint default 0, change `depth` `depth` tinyint default 0]\\n[native code: 1068]\\n[native message: multiple primary key defined]\\n)\",\"level\":4,\"time\":1374433240}</code>\r\n\r\nthis is on a debian-vm, using postgresql (9.3) as the db-backend"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21452438","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21452438","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21452438,"user":{"login":"tanatospl","id":2816499,"avatar_url":"https://gravatar.com/avatar/c88ee51b388c558d5fa0ad8b2cc530e9?d=https%3a%2f%2fidenticons.github.com%2fcf6bbd45003a0a895e3550f329a948dd.png&r=x","gravatar_id":"c88ee51b388c558d5fa0ad8b2cc530e9","url":"https://api.github.com/users/tanatospl","html_url":"https://github.com/tanatospl","followers_url":"https://api.github.com/users/tanatospl/followers","following_url":"https://api.github.com/users/tanatospl/following{/other_user}","gists_url":"https://api.github.com/users/tanatospl/gists{/gist_id}","starred_url":"https://api.github.com/users/tanatospl/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tanatospl/subscriptions","organizations_url":"https://api.github.com/users/tanatospl/orgs","repos_url":"https://api.github.com/users/tanatospl/repos","events_url":"https://api.github.com/users/tanatospl/events{/privacy}","received_events_url":"https://api.github.com/users/tanatospl/received_events","type":"user","site_admin":false},"created_at":"2013-07-23t22:56:39z","updated_at":"2013-07-23t22:56:39z","body":"i had this problem too (multiple primary key defined).\r\n\r\nthe problem here is that mysql does not allow to alter primary key of a table without deleting that key first. \r\ni fixed this problem by going to phpmyadmin and manually deleting primary keys for tables like: locks, queuedtasks, vcategory, calendar* etc... and then refreshing my owncloud page. this restarted the update procedure and fixed the problem.\r\n\r\nthe long term fix would be to change the owncloud updater code to always add \"alter table tablename drop primary key\" before executing any primary key altering on mysql."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21466858","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21466858","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21466858,"user":{"login":"valleygeek","id":5023191,"avatar_url":"https://gravatar.com/avatar/cc4caf88c02c37a391cf31ac66c72a22?d=https%3a%2f%2fidenticons.github.com%2fdc47389544535b41a12decad5216d019.png&r=x","gravatar_id":"cc4caf88c02c37a391cf31ac66c72a22","url":"https://api.github.com/users/valleygeek","html_url":"https://github.com/valleygeek","followers_url":"https://api.github.com/users/valleygeek/followers","following_url":"https://api.github.com/users/valleygeek/following{/other_user}","gists_url":"https://api.github.com/users/valleygeek/gists{/gist_id}","starred_url":"https://api.github.com/users/valleygeek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/valleygeek/subscriptions","organizations_url":"https://api.github.com/users/valleygeek/orgs","repos_url":"https://api.github.com/users/valleygeek/repos","events_url":"https://api.github.com/users/valleygeek/events{/privacy}","received_events_url":"https://api.github.com/users/valleygeek/received_events","type":"user","site_admin":false},"created_at":"2013-07-24t06:50:05z","updated_at":"2013-07-24t06:50:05z","body":"following the advice of @tanatospl i ran the commands below against my database (one at a time) refreshing my owncloud root page after each table change and have successfully completed the update with no changes other than what has been mentioned in this issue.\r\n\r\nthe first line in each pair was to remove the \"auto increment\" from the id fields (mysql error: \"error 1075 (42000): incorrect table definition; there can be only one auto column and it must be defined as a key\") and the second is to remove the primary key attribute.\r\n\r\n```mysql\r\nalter table `oc_locks` change `id` `id` int( 11 ) not null;\r\nalter table `oc_locks` drop primary key;\r\nalter table `oc_queuedtasks` change `id` `id` int( 11 ) not null;\r\nalter table `oc_queuedtasks` drop primary key;\r\nalter table `oc_vcategory` change `id` `id` int( 11 ) not null;\r\nalter table `oc_vcategory` drop primary key;\r\n```\r\n\r\nat this time i am no longer affected by this issue. i proceeded to immediately run the auto update from 5.0.8 to 5.0.9 and it ran without issue. i didn't close this issue in the event that others are still receiving this and it should be left open but i have no personal reason for it to be left open."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21681242","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21681242","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21681242,"user":{"login":"brotkastn","id":604466,"avatar_url":"https://gravatar.com/avatar/4df8961b07bfc513f454f82a6d9bd21c?d=https%3a%2f%2fidenticons.github.com%2f9da986bb5f8b2429ae26abf0b53de926.png&r=x","gravatar_id":"4df8961b07bfc513f454f82a6d9bd21c","url":"https://api.github.com/users/brotkastn","html_url":"https://github.com/brotkastn","followers_url":"https://api.github.com/users/brotkastn/followers","following_url":"https://api.github.com/users/brotkastn/following{/other_user}","gists_url":"https://api.github.com/users/brotkastn/gists{/gist_id}","starred_url":"https://api.github.com/users/brotkastn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/brotkastn/subscriptions","organizations_url":"https://api.github.com/users/brotkastn/orgs","repos_url":"https://api.github.com/users/brotkastn/repos","events_url":"https://api.github.com/users/brotkastn/events{/privacy}","received_events_url":"https://api.github.com/users/brotkastn/received_events","type":"user","site_admin":false},"created_at":"2013-07-28t10:13:52z","updated_at":"2013-07-28t10:13:52z","body":"so, what is the official way to upgrade then? since i guess it shouldnt involve the users to execute own statements like @valleygeek , i guess the upgrade script should check which db it runs on and try to do the right thing."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21681850","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21681850","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21681850,"user":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false},"created_at":"2013-07-28t11:02:42z","updated_at":"2013-07-28t11:02:42z","body":"could you try to upgrade to 5.0.9 please? we fixed a few bugs here. "},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/21681963","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-21681963","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":21681963,"user":{"login":"brotkastn","id":604466,"avatar_url":"https://gravatar.com/avatar/4df8961b07bfc513f454f82a6d9bd21c?d=https%3a%2f%2fidenticons.github.com%2f9da986bb5f8b2429ae26abf0b53de926.png&r=x","gravatar_id":"4df8961b07bfc513f454f82a6d9bd21c","url":"https://api.github.com/users/brotkastn","html_url":"https://github.com/brotkastn","followers_url":"https://api.github.com/users/brotkastn/followers","following_url":"https://api.github.com/users/brotkastn/following{/other_user}","gists_url":"https://api.github.com/users/brotkastn/gists{/gist_id}","starred_url":"https://api.github.com/users/brotkastn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/brotkastn/subscriptions","organizations_url":"https://api.github.com/users/brotkastn/orgs","repos_url":"https://api.github.com/users/brotkastn/repos","events_url":"https://api.github.com/users/brotkastn/events{/privacy}","received_events_url":"https://api.github.com/users/brotkastn/received_events","type":"user","site_admin":false},"created_at":"2013-07-28t11:10:51z","updated_at":"2013-07-28t11:10:51z","body":"as stated before, this was while trying to upgrade to 5.0.9."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/23055857","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-23055857","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":23055857,"user":{"login":"brotkastn","id":604466,"avatar_url":"https://gravatar.com/avatar/4df8961b07bfc513f454f82a6d9bd21c?d=https%3a%2f%2fidenticons.github.com%2f9da986bb5f8b2429ae26abf0b53de926.png&r=x","gravatar_id":"4df8961b07bfc513f454f82a6d9bd21c","url":"https://api.github.com/users/brotkastn","html_url":"https://github.com/brotkastn","followers_url":"https://api.github.com/users/brotkastn/followers","following_url":"https://api.github.com/users/brotkastn/following{/other_user}","gists_url":"https://api.github.com/users/brotkastn/gists{/gist_id}","starred_url":"https://api.github.com/users/brotkastn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/brotkastn/subscriptions","organizations_url":"https://api.github.com/users/brotkastn/orgs","repos_url":"https://api.github.com/users/brotkastn/repos","events_url":"https://api.github.com/users/brotkastn/events{/privacy}","received_events_url":"https://api.github.com/users/brotkastn/received_events","type":"user","site_admin":false},"created_at":"2013-08-21t22:35:27z","updated_at":"2013-08-21t22:35:27z","body":"after trying to upgrade to 5.0.10, this is what the owncloud.log contains.\r\n\r\n```{\"app\":\"core\",\"message\":\"failed to update database structure (mdb2 error: unknown error, _doquery:\r\n [error message: could not execute statement]\r\n\\n[last executed query: alter table `oc_calendar_objects` rename to `oc_clndr_objects`, change `id` `id` \r\nint unsigned not null auto_increment primary key, change `calendarid` `calendarid` int \r\nunsigned default 0 not null, change `startdate` `startdate` datetime default '1970-01-01 00:00:00', \r\nchange `enddate` `enddate` datetime default '1970-01-01 00:00:00']\r\n\\n[native code: 1068]\r\n\\n[native message: multiple primary key defined]\\n)\",\"level\":4,\"time\":\"2013-08-21t22:26:08+00:00\"}```\r\n\r\n"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/23070358","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-23070358","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":23070358,"user":{"login":"realrancor","id":2248459,"avatar_url":"https://gravatar.com/avatar/f6105e79dfcfb0fcbabb3db061135c08?d=https%3a%2f%2fidenticons.github.com%2f7a70061016eba74d85c060de0f65212d.png&r=x","gravatar_id":"f6105e79dfcfb0fcbabb3db061135c08","url":"https://api.github.com/users/realrancor","html_url":"https://github.com/realrancor","followers_url":"https://api.github.com/users/realrancor/followers","following_url":"https://api.github.com/users/realrancor/following{/other_user}","gists_url":"https://api.github.com/users/realrancor/gists{/gist_id}","starred_url":"https://api.github.com/users/realrancor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/realrancor/subscriptions","organizations_url":"https://api.github.com/users/realrancor/orgs","repos_url":"https://api.github.com/users/realrancor/repos","events_url":"https://api.github.com/users/realrancor/events{/privacy}","received_events_url":"https://api.github.com/users/realrancor/received_events","type":"user","site_admin":false},"created_at":"2013-08-22t06:08:06z","updated_at":"2013-08-22t06:08:06z","body":"hi,\r\n\r\nsee https://github.com/owncloud/core/issues/4013 on how to fix this."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/24310709","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-24310709","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":24310709,"user":{"login":"strangenoises","id":1295001,"avatar_url":"https://gravatar.com/avatar/a5d6612a9a7da64e0e878d1b3bc04d8a?d=https%3a%2f%2fidenticons.github.com%2f3d85d3be1f7025aa7ef230d575c85d82.png&r=x","gravatar_id":"a5d6612a9a7da64e0e878d1b3bc04d8a","url":"https://api.github.com/users/strangenoises","html_url":"https://github.com/strangenoises","followers_url":"https://api.github.com/users/strangenoises/followers","following_url":"https://api.github.com/users/strangenoises/following{/other_user}","gists_url":"https://api.github.com/users/strangenoises/gists{/gist_id}","starred_url":"https://api.github.com/users/strangenoises/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/strangenoises/subscriptions","organizations_url":"https://api.github.com/users/strangenoises/orgs","repos_url":"https://api.github.com/users/strangenoises/repos","events_url":"https://api.github.com/users/strangenoises/events{/privacy}","received_events_url":"https://api.github.com/users/strangenoises/received_events","type":"user","site_admin":false},"created_at":"2013-09-12t11:17:31z","updated_at":"2013-09-12t11:17:31z","body":"is this a won't-fix? seeing as it is still affecting the most recent upgrade, and according to comments here it seems to also affect a postgresql backend, i'm surprised to find no apparent interest in actually fixing the bug. it's not acceptable to expect users to hack around in the database for every upgrade.\r\n\r\nguess i'll go back to reading about git-annex; interrupted when i thought owncloud would be easier and less hassle."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/24325346","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-24325346","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":24325346,"user":{"login":"vicdeo","id":991300,"avatar_url":"https://gravatar.com/avatar/57b8c1e26d502d5414e4b2fb875d2994?d=https%3a%2f%2fidenticons.github.com%2fe8357fefe8bad5436de368fa5a419461.png&r=x","gravatar_id":"57b8c1e26d502d5414e4b2fb875d2994","url":"https://api.github.com/users/vicdeo","html_url":"https://github.com/vicdeo","followers_url":"https://api.github.com/users/vicdeo/followers","following_url":"https://api.github.com/users/vicdeo/following{/other_user}","gists_url":"https://api.github.com/users/vicdeo/gists{/gist_id}","starred_url":"https://api.github.com/users/vicdeo/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vicdeo/subscriptions","organizations_url":"https://api.github.com/users/vicdeo/orgs","repos_url":"https://api.github.com/users/vicdeo/repos","events_url":"https://api.github.com/users/vicdeo/events{/privacy}","received_events_url":"https://api.github.com/users/vicdeo/received_events","type":"user","site_admin":false},"created_at":"2013-09-12t14:39:53z","updated_at":"2013-09-12t14:40:09z","body":"@strangenoises fixed in master for oc6 milestone afaik. \r\nwon't fix for stable5 most likely since oc6 uses different dbal.\r\n\r\n i never was able to reproduce db-related issues on upgrade for a dozen development installations and a production instance i use to communicate with my relatives which was installed as 4.5.4 and survived in a number of upgrades to the current  5.0.10 "},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/24458594","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-24458594","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":24458594,"user":{"login":"mokkin","id":2938748,"avatar_url":"https://gravatar.com/avatar/8a617cfcd4ed1e12691b24b76704940a?d=https%3a%2f%2fidenticons.github.com%2f6ad6136bce2431f4f1940265fd3d2841.png&r=x","gravatar_id":"8a617cfcd4ed1e12691b24b76704940a","url":"https://api.github.com/users/mokkin","html_url":"https://github.com/mokkin","followers_url":"https://api.github.com/users/mokkin/followers","following_url":"https://api.github.com/users/mokkin/following{/other_user}","gists_url":"https://api.github.com/users/mokkin/gists{/gist_id}","starred_url":"https://api.github.com/users/mokkin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mokkin/subscriptions","organizations_url":"https://api.github.com/users/mokkin/orgs","repos_url":"https://api.github.com/users/mokkin/repos","events_url":"https://api.github.com/users/mokkin/events{/privacy}","received_events_url":"https://api.github.com/users/mokkin/received_events","type":"user","site_admin":false},"created_at":"2013-09-14t20:34:09z","updated_at":"2013-09-14t20:34:09z","body":"same here too.\r\nubuntu 12.04 / oc 5.0.11"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/24458642","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-24458642","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":24458642,"user":{"login":"strangenoises","id":1295001,"avatar_url":"https://gravatar.com/avatar/a5d6612a9a7da64e0e878d1b3bc04d8a?d=https%3a%2f%2fidenticons.github.com%2f3d85d3be1f7025aa7ef230d575c85d82.png&r=x","gravatar_id":"a5d6612a9a7da64e0e878d1b3bc04d8a","url":"https://api.github.com/users/strangenoises","html_url":"https://github.com/strangenoises","followers_url":"https://api.github.com/users/strangenoises/followers","following_url":"https://api.github.com/users/strangenoises/following{/other_user}","gists_url":"https://api.github.com/users/strangenoises/gists{/gist_id}","starred_url":"https://api.github.com/users/strangenoises/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/strangenoises/subscriptions","organizations_url":"https://api.github.com/users/strangenoises/orgs","repos_url":"https://api.github.com/users/strangenoises/repos","events_url":"https://api.github.com/users/strangenoises/events{/privacy}","received_events_url":"https://api.github.com/users/strangenoises/received_events","type":"user","site_admin":false},"created_at":"2013-09-14t20:36:49z","updated_at":"2013-09-14t20:36:49z","body":"for my part, after a mini-adventure with git-annex which actually managed to break my time machine drive (!) i'm back, having done the necessary manual changes to the db to allow the upgrade to take place as described in a comment above. but still. grr."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/24498112","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-24498112","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":24498112,"user":{"login":"a-schild","id":1441009,"avatar_url":"https://gravatar.com/avatar/836ed996b63a770fb92cbe40ea29586a?d=https%3a%2f%2fidenticons.github.com%2fd18ec31dde04f2ca5deeb18b0e209801.png&r=x","gravatar_id":"836ed996b63a770fb92cbe40ea29586a","url":"https://api.github.com/users/a-schild","html_url":"https://github.com/a-schild","followers_url":"https://api.github.com/users/a-schild/followers","following_url":"https://api.github.com/users/a-schild/following{/other_user}","gists_url":"https://api.github.com/users/a-schild/gists{/gist_id}","starred_url":"https://api.github.com/users/a-schild/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/a-schild/subscriptions","organizations_url":"https://api.github.com/users/a-schild/orgs","repos_url":"https://api.github.com/users/a-schild/repos","events_url":"https://api.github.com/users/a-schild/events{/privacy}","received_events_url":"https://api.github.com/users/a-schild/received_events","type":"user","site_admin":false},"created_at":"2013-09-16t09:28:52z","updated_at":"2013-09-16t09:28:52z","body":"just stumbled into this one on a installation from 5.0.8 to 5.0.11 (many other such upgrades did work flawlessly)"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/25482070","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-25482070","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":25482070,"user":{"login":"franzhartwig","id":5375423,"avatar_url":"https://gravatar.com/avatar/a702f6ab3eef892c427011db8ea7ef0e?d=https%3a%2f%2fidenticons.github.com%2f65f75933a276a889ada1c9e49eb36b70.png&r=x","gravatar_id":"a702f6ab3eef892c427011db8ea7ef0e","url":"https://api.github.com/users/franzhartwig","html_url":"https://github.com/franzhartwig","followers_url":"https://api.github.com/users/franzhartwig/followers","following_url":"https://api.github.com/users/franzhartwig/following{/other_user}","gists_url":"https://api.github.com/users/franzhartwig/gists{/gist_id}","starred_url":"https://api.github.com/users/franzhartwig/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/franzhartwig/subscriptions","organizations_url":"https://api.github.com/users/franzhartwig/orgs","repos_url":"https://api.github.com/users/franzhartwig/repos","events_url":"https://api.github.com/users/franzhartwig/events{/privacy}","received_events_url":"https://api.github.com/users/franzhartwig/received_events","type":"user","site_admin":false},"created_at":"2013-10-01t19:49:44z","updated_at":"2013-10-01t19:49:44z","body":"upgrade from 5.0.6 to 5.0.10 and from 5.0.6 to 5.0.11 failed with this mysql error. i tried a manual update and an update with the updater. runnung 5.0.6 again."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29517478","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29517478","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29517478,"user":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false},"created_at":"2013-11-29t13:57:52z","updated_at":"2013-11-29t13:57:52z","body":"is it possible that you manually migrated for sqlite to mysql?"},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29518268","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29518268","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29518268,"user":{"login":"strangenoises","id":1295001,"avatar_url":"https://gravatar.com/avatar/a5d6612a9a7da64e0e878d1b3bc04d8a?d=https%3a%2f%2fidenticons.github.com%2f3d85d3be1f7025aa7ef230d575c85d82.png&r=x","gravatar_id":"a5d6612a9a7da64e0e878d1b3bc04d8a","url":"https://api.github.com/users/strangenoises","html_url":"https://github.com/strangenoises","followers_url":"https://api.github.com/users/strangenoises/followers","following_url":"https://api.github.com/users/strangenoises/following{/other_user}","gists_url":"https://api.github.com/users/strangenoises/gists{/gist_id}","starred_url":"https://api.github.com/users/strangenoises/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/strangenoises/subscriptions","organizations_url":"https://api.github.com/users/strangenoises/orgs","repos_url":"https://api.github.com/users/strangenoises/repos","events_url":"https://api.github.com/users/strangenoises/events{/privacy}","received_events_url":"https://api.github.com/users/strangenoises/received_events","type":"user","site_admin":false},"created_at":"2013-11-29t14:11:58z","updated_at":"2013-11-29t14:11:58z","body":"replying here as you just closed my duplicate.\r\n\r\nof course. if there's a non-manual way, it's very non-obvious. as i reported in the other report, i just followed http://fabianpeter.de/cloud/owncloud-migrating-from-sqlite-to-mysql/ as the only guide i could find on the subject.\r\n\r\nit's quite annoying; as basically *every* minor owncloud update initially fails with this error on some random table (always a different one). i dread the upgrade to owncloud 6."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29522196","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29522196","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29522196,"user":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false},"created_at":"2013-11-29t15:21:01z","updated_at":"2013-11-29t15:21:01z","body":"thanks for the link. i contacted the author so that he can put a warning on the blog. "},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29522284","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29522284","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29522284,"user":{"login":"strangenoises","id":1295001,"avatar_url":"https://gravatar.com/avatar/a5d6612a9a7da64e0e878d1b3bc04d8a?d=https%3a%2f%2fidenticons.github.com%2f3d85d3be1f7025aa7ef230d575c85d82.png&r=x","gravatar_id":"a5d6612a9a7da64e0e878d1b3bc04d8a","url":"https://api.github.com/users/strangenoises","html_url":"https://github.com/strangenoises","followers_url":"https://api.github.com/users/strangenoises/followers","following_url":"https://api.github.com/users/strangenoises/following{/other_user}","gists_url":"https://api.github.com/users/strangenoises/gists{/gist_id}","starred_url":"https://api.github.com/users/strangenoises/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/strangenoises/subscriptions","organizations_url":"https://api.github.com/users/strangenoises/orgs","repos_url":"https://api.github.com/users/strangenoises/repos","events_url":"https://api.github.com/users/strangenoises/events{/privacy}","received_events_url":"https://api.github.com/users/strangenoises/received_events","type":"user","site_admin":false},"created_at":"2013-11-29t15:22:29z","updated_at":"2013-11-29t15:22:29z","body":"so what you're saying is, there is no proper way to switch to mysql? i mean, despite these niggles, it actually works a hell of a lot faster on the same server when there are multiple clients..."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29524463","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29524463","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29524463,"user":{"login":"ayedoit","id":3606184,"avatar_url":"https://gravatar.com/avatar/75026c0902e5488012f29415da983693?d=https%3a%2f%2fidenticons.github.com%2f3095bc6808cb7e60d38709927a910f26.png&r=x","gravatar_id":"75026c0902e5488012f29415da983693","url":"https://api.github.com/users/ayedoit","html_url":"https://github.com/ayedoit","followers_url":"https://api.github.com/users/ayedoit/followers","following_url":"https://api.github.com/users/ayedoit/following{/other_user}","gists_url":"https://api.github.com/users/ayedoit/gists{/gist_id}","starred_url":"https://api.github.com/users/ayedoit/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ayedoit/subscriptions","organizations_url":"https://api.github.com/users/ayedoit/orgs","repos_url":"https://api.github.com/users/ayedoit/repos","events_url":"https://api.github.com/users/ayedoit/events{/privacy}","received_events_url":"https://api.github.com/users/ayedoit/received_events","type":"user","site_admin":false},"created_at":"2013-11-29t16:00:53z","updated_at":"2013-11-29t16:01:51z","body":"hi,\r\n\r\nas the author of the mentioned blog post, i wanted to give my 2 cents here, too. \r\n\r\naccording to my research so far, i think the problem comes from unstraight table definitions in in the structure schema. \r\n\r\nsee https://github.com/owncloud/core/blob/master/db_structure.xml:\r\n\r\n```xml\r\n                        <field>\r\n                                <name>id</name>\r\n                                <type>integer</type>\r\n                                <default>0</default>\r\n                                <notnull>true</notnull>\r\n                                <autoincrement>1</autoincrement>\r\n                                <unsigned>true</unsigned>\r\n                                <length>4</length>\r\n                        </field>\r\n```\r\n\"id\" is not defined as primary key, though it will be marked as primary key as soon as you create or at least dump the database in sqlite. the python script then reads the \"primary key\" information and of course migrates it to mysql-syntax (which, in fact, only means to exchange \" with `). \r\n\r\nif you take a look at the sqlite-schema of the table in question (oc_locks), you will see that \"id\" is defined as primary key here - although not defined as such in \"db_structure.xml\":\r\n\r\n```sql\r\nsqlite> .schema oc_locks\r\ncreate table \"oc_locks\" (\"id\" integer primary key autoincrement, \"userid\" varchar(64), \"owner\" varchar(100), \"timeout\" integer unsigned default 0, \"created\" bigint default 0, \"token\" varchar(100), \"scope\" smallint default 0, \"depth\" smallint default 0, \"uri\" longtext);\r\n```\r\nso the conversion works correct and the python script works correct. \r\n\r\nsomeone mentioned, that it helps to drop the primary index before the alternation in the upgrade process, which makes sense. basically, this should be considered in the upgrade process and in the creation process (i.e. db_structure.xml). just define a proper index and just handle this when altering the table on upgrade."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29524838","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29524838","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29524838,"user":{"login":"vicdeo","id":991300,"avatar_url":"https://gravatar.com/avatar/57b8c1e26d502d5414e4b2fb875d2994?d=https%3a%2f%2fidenticons.github.com%2fe8357fefe8bad5436de368fa5a419461.png&r=x","gravatar_id":"57b8c1e26d502d5414e4b2fb875d2994","url":"https://api.github.com/users/vicdeo","html_url":"https://github.com/vicdeo","followers_url":"https://api.github.com/users/vicdeo/followers","following_url":"https://api.github.com/users/vicdeo/following{/other_user}","gists_url":"https://api.github.com/users/vicdeo/gists{/gist_id}","starred_url":"https://api.github.com/users/vicdeo/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vicdeo/subscriptions","organizations_url":"https://api.github.com/users/vicdeo/orgs","repos_url":"https://api.github.com/users/vicdeo/repos","events_url":"https://api.github.com/users/vicdeo/events{/privacy}","received_events_url":"https://api.github.com/users/vicdeo/received_events","type":"user","site_admin":false},"created_at":"2013-11-29t16:08:06z","updated_at":"2013-11-29t16:08:24z","body":"indeed, oc_locks schema has no `index`  section but the table has indexes.\r\nthat might be the cause."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29524991","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29524991","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29524991,"user":{"login":"strangenoises","id":1295001,"avatar_url":"https://gravatar.com/avatar/a5d6612a9a7da64e0e878d1b3bc04d8a?d=https%3a%2f%2fidenticons.github.com%2f3d85d3be1f7025aa7ef230d575c85d82.png&r=x","gravatar_id":"a5d6612a9a7da64e0e878d1b3bc04d8a","url":"https://api.github.com/users/strangenoises","html_url":"https://github.com/strangenoises","followers_url":"https://api.github.com/users/strangenoises/followers","following_url":"https://api.github.com/users/strangenoises/following{/other_user}","gists_url":"https://api.github.com/users/strangenoises/gists{/gist_id}","starred_url":"https://api.github.com/users/strangenoises/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/strangenoises/subscriptions","organizations_url":"https://api.github.com/users/strangenoises/orgs","repos_url":"https://api.github.com/users/strangenoises/repos","events_url":"https://api.github.com/users/strangenoises/events{/privacy}","received_events_url":"https://api.github.com/users/strangenoises/received_events","type":"user","site_admin":false},"created_at":"2013-11-29t16:10:42z","updated_at":"2013-11-29t16:10:42z","body":"every time there's a minor upgrade, it's a different table that needs fixing; but it's always the same problem; the fix being to remove the primary key index and then try the command listed in the error message again. it seems odd to me that it only errors on one table per upgrade and then is seemingly happy with the rest, until the next upgrade, when the next table needs it done..."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29525642","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29525642","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29525642,"user":{"login":"strangenoises","id":1295001,"avatar_url":"https://gravatar.com/avatar/a5d6612a9a7da64e0e878d1b3bc04d8a?d=https%3a%2f%2fidenticons.github.com%2f3d85d3be1f7025aa7ef230d575c85d82.png&r=x","gravatar_id":"a5d6612a9a7da64e0e878d1b3bc04d8a","url":"https://api.github.com/users/strangenoises","html_url":"https://github.com/strangenoises","followers_url":"https://api.github.com/users/strangenoises/followers","following_url":"https://api.github.com/users/strangenoises/following{/other_user}","gists_url":"https://api.github.com/users/strangenoises/gists{/gist_id}","starred_url":"https://api.github.com/users/strangenoises/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/strangenoises/subscriptions","organizations_url":"https://api.github.com/users/strangenoises/orgs","repos_url":"https://api.github.com/users/strangenoises/repos","events_url":"https://api.github.com/users/strangenoises/events{/privacy}","received_events_url":"https://api.github.com/users/strangenoises/received_events","type":"user","site_admin":false},"created_at":"2013-11-29t16:21:35z","updated_at":"2013-11-29t16:21:35z","body":"i first encountered this on 5.0.11 (before which i switched to mysql) (reported originally in my now-closed dupe bug #4809, now on 5.0.13 so actually it's only happened 3 times for me. fyi my entire .mysql_history from that time:\r\n\r\n````\r\nshow create table oc_locks;\r\ndescribe oc_locks;\r\nalter table `oc_locks` change `id` `id` int( 11 ) not null;\r\nalter table `oc_locks` drop primary key;\r\ndescribe oc_queuedtasks;\r\ndescribe oc_locks;\r\nalter table `oc_queuedtasks` change `id` `id` int( 11 ) not null;\r\nalter table `oc_queuedtasks` drop primary key;\r\nalter table `oc_vcategory` drop primary key;\r\ndescribe oc_vcategory\r\n;\r\nalter table `oc_vcategory` drop primary key;\r\nalter table `oc_vcategory` change `id` `id` int unsigned not null;\r\ndescribe oc_vcategory;\r\nalter table `oc_vcategory` change `id` `id` int unsigned not null auto_increment primary key;\r\ndescribe oc_vcategory;\r\nalter table `oc_vcategory` drop primary key;\r\ndescribe oc_vcategory;\r\nalter table `oc_vcategory` change `id` `id` int unsigned not null auto_increment primary key;\r\ndescribe oc_vcategory;\r\nalter table `oc_vcategory` change `uid` `uid` varchar(64) default ' ' not null, change `type` `type` varchar(64) default ' ' not null, change `category` `category` varchar(255) default ' ' not null;\r\ndescribe oc_vcategory;\r\n````\r\n\r\n... which reminds me i did have some extra problem with the most recent time, with oc_vcategory.\r\n\r\nbut mostly included in case the order in which the tables are failing is illuminating..."},{"url":"https://api.github.com/repos/owncloud/core/issues/comments/29891888","html_url":"https://github.com/owncloud/core/issues/4085#issuecomment-29891888","issue_url":"https://api.github.com/repos/owncloud/core/issues/4085","id":29891888,"user":{"login":"ayedoit","id":3606184,"avatar_url":"https://gravatar.com/avatar/75026c0902e5488012f29415da983693?d=https%3a%2f%2fidenticons.github.com%2f3095bc6808cb7e60d38709927a910f26.png&r=x","gravatar_id":"75026c0902e5488012f29415da983693","url":"https://api.github.com/users/ayedoit","html_url":"https://github.com/ayedoit","followers_url":"https://api.github.com/users/ayedoit/followers","following_url":"https://api.github.com/users/ayedoit/following{/other_user}","gists_url":"https://api.github.com/users/ayedoit/gists{/gist_id}","starred_url":"https://api.github.com/users/ayedoit/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ayedoit/subscriptions","organizations_url":"https://api.github.com/users/ayedoit/orgs","repos_url":"https://api.github.com/users/ayedoit/repos","events_url":"https://api.github.com/users/ayedoit/events{/privacy}","received_events_url":"https://api.github.com/users/ayedoit/received_events","type":"user","site_admin":false},"created_at":"2013-12-05t11:56:58z","updated_at":"2013-12-05t11:56:58z","body":"so you're saying, you already had the problem before the migration?"}]