{"url":"https://api.github.com/repos/owncloud/core/issues/2137","labels_url":"https://api.github.com/repos/owncloud/core/issues/2137/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/2137/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/2137/events","html_url":"https://github.com/owncloud/core/issues/2137","id":11714993,"number":2137,"title":"mdb2_schema error at update to 5.0","user":{"login":"friedmar","id":3788116,"avatar_url":"https://gravatar.com/avatar/ee4d1a7e17d645b65dd1b19cadde4f3b?d=https%3a%2f%2fidenticons.github.com%2f5922c2001e93d7ee2cfcc2f3588e414a.png&r=x","gravatar_id":"ee4d1a7e17d645b65dd1b19cadde4f3b","url":"https://api.github.com/users/friedmar","html_url":"https://github.com/friedmar","followers_url":"https://api.github.com/users/friedmar/followers","following_url":"https://api.github.com/users/friedmar/following{/other_user}","gists_url":"https://api.github.com/users/friedmar/gists{/gist_id}","starred_url":"https://api.github.com/users/friedmar/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/friedmar/subscriptions","organizations_url":"https://api.github.com/users/friedmar/orgs","repos_url":"https://api.github.com/users/friedmar/repos","events_url":"https://api.github.com/users/friedmar/events{/privacy}","received_events_url":"https://api.github.com/users/friedmar/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/needs+info","name":"needs info","color":"0b02e1"}],"state":"closed","assignee":null,"milestone":null,"comments":13,"created_at":"2013-03-06t14:37:07z","updated_at":"2013-10-18t20:37:34z","closed_at":"2013-03-07t20:14:41z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"updating owncloud to version 5.0 rc 2, this may take a while.\r\n\r\nturned on maintenance mode\r\nfailed to get existing database structure for updating (mdb2_schema error: schema validation error, default value of \"visitor_localtime\" is incorrect: \"\" is not of type \"time\")\r\n\r\nthe update was unsuccessful. please report this issue to the owncloud community.","closed_by":{"login":"friedmar","id":3788116,"avatar_url":"https://gravatar.com/avatar/ee4d1a7e17d645b65dd1b19cadde4f3b?d=https%3a%2f%2fidenticons.github.com%2f5922c2001e93d7ee2cfcc2f3588e414a.png&r=x","gravatar_id":"ee4d1a7e17d645b65dd1b19cadde4f3b","url":"https://api.github.com/users/friedmar","html_url":"https://github.com/friedmar","followers_url":"https://api.github.com/users/friedmar/followers","following_url":"https://api.github.com/users/friedmar/following{/other_user}","gists_url":"https://api.github.com/users/friedmar/gists{/gist_id}","starred_url":"https://api.github.com/users/friedmar/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/friedmar/subscriptions","organizations_url":"https://api.github.com/users/friedmar/orgs","repos_url":"https://api.github.com/users/friedmar/repos","events_url":"https://api.github.com/users/friedmar/events{/privacy}","received_events_url":"https://api.github.com/users/friedmar/received_events","type":"user","site_admin":false}}