{"url":"https://api.github.com/repos/owncloud/core/issues/3133","labels_url":"https://api.github.com/repos/owncloud/core/issues/3133/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/3133/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/3133/events","html_url":"https://github.com/owncloud/core/issues/3133","id":13649678,"number":3133,"title":"desktop client does not sync files updated on the server","user":{"login":"olunet","id":526920,"avatar_url":"https://gravatar.com/avatar/e88792a34165d0d449ebcd442300e1c8?d=https%3a%2f%2fidenticons.github.com%2f1ccf2c0f644a95feff545cf743c18f81.png&r=x","gravatar_id":"e88792a34165d0d449ebcd442300e1c8","url":"https://api.github.com/users/olunet","html_url":"https://github.com/olunet","followers_url":"https://api.github.com/users/olunet/followers","following_url":"https://api.github.com/users/olunet/following{/other_user}","gists_url":"https://api.github.com/users/olunet/gists{/gist_id}","starred_url":"https://api.github.com/users/olunet/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/olunet/subscriptions","organizations_url":"https://api.github.com/users/olunet/orgs","repos_url":"https://api.github.com/users/olunet/repos","events_url":"https://api.github.com/users/olunet/events{/privacy}","received_events_url":"https://api.github.com/users/olunet/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2013-04-25t17:02:32z","updated_at":"2013-04-25t18:04:32z","closed_at":"2013-04-25t18:04:32z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"os: ubuntu 12.04, oc: 4.5.9 (linux,sqlite), client 1.2.5\r\n\r\n1) added figure.eps to a folder synced via the desktop client. the file appeared in a shared directory in the webui.\r\n2) modified the figure.eps and uploaded it to the cloud not using the client. the update is visible in the webui.\r\n3) unfortunately, the desktop client does not download the file from the cloud.\r\n4) testing with simple text-file are successful, but for some reason some files, e.g. figure.eps in my case, are not synced as expected.\r\nhere is a link to a similar case: http://forum.owncloud.org/viewtopic.php?f=14&t=9553#p23619","closed_by":{"login":"kabum","id":245432,"avatar_url":"https://gravatar.com/avatar/a1dea19f88f38ea0b5b5b4d19d5b3107?d=https%3a%2f%2fidenticons.github.com%2f53d8cbb3dbc087a02951dec47438ccdf.png&r=x","gravatar_id":"a1dea19f88f38ea0b5b5b4d19d5b3107","url":"https://api.github.com/users/kabum","html_url":"https://github.com/kabum","followers_url":"https://api.github.com/users/kabum/followers","following_url":"https://api.github.com/users/kabum/following{/other_user}","gists_url":"https://api.github.com/users/kabum/gists{/gist_id}","starred_url":"https://api.github.com/users/kabum/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kabum/subscriptions","organizations_url":"https://api.github.com/users/kabum/orgs","repos_url":"https://api.github.com/users/kabum/repos","events_url":"https://api.github.com/users/kabum/events{/privacy}","received_events_url":"https://api.github.com/users/kabum/received_events","type":"user","site_admin":false}}