{"url":"https://api.github.com/repos/owncloud/core/issues/5513","labels_url":"https://api.github.com/repos/owncloud/core/issues/5513/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/5513/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/5513/events","html_url":"https://github.com/owncloud/core/pull/5513","id":21514309,"number":5513,"title":"fix file cache updater","user":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":19,"created_at":"2013-10-24t10:40:18z","updated_at":"2013-10-30t09:49:36z","closed_at":"2013-10-29t13:40:08z","pull_request":{"html_url":"https://github.com/owncloud/core/pull/5513","diff_url":"https://github.com/owncloud/core/pull/5513.diff","patch_url":"https://github.com/owncloud/core/pull/5513.patch"},"body":"this fixes bug https://github.com/owncloud/core/issues/5098\r\nfor a detailed explanation how to reproduce it look at: https://github.com/owncloud/mirall/issues/1056#issuecomment-25524490\r\n\r\n@icewind1991 please have a look. correctfolder() always assumed that we are operating on a folder owned by the current user which of course is wrong in case of a shared file. that's why i changed resolvepath() to resolve the path to the owners path and updated the correctfolder() method to loop though the correct folder tree.\r\n\r\nalso affects master, will port it once the fix is merged for stable5.","closed_by":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false}}