{"url":"https://api.github.com/repos/owncloud/core/issues/6440","labels_url":"https://api.github.com/repos/owncloud/core/issues/6440/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/6440/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/6440/events","html_url":"https://github.com/owncloud/core/issues/6440","id":24351437,"number":6440,"title":"[6.0.0a] client upload of some (jpg) files fail","user":{"login":"jcfischer","id":3088,"avatar_url":"https://gravatar.com/avatar/5085ba37ba624a788e04a842cd09bd6e?d=https%3a%2f%2fidenticons.github.com%2fdc6a7e655d7e5840e66733e9ee67cc69.png&r=x","gravatar_id":"5085ba37ba624a788e04a842cd09bd6e","url":"https://api.github.com/users/jcfischer","html_url":"https://github.com/jcfischer","followers_url":"https://api.github.com/users/jcfischer/followers","following_url":"https://api.github.com/users/jcfischer/following{/other_user}","gists_url":"https://api.github.com/users/jcfischer/gists{/gist_id}","starred_url":"https://api.github.com/users/jcfischer/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jcfischer/subscriptions","organizations_url":"https://api.github.com/users/jcfischer/orgs","repos_url":"https://api.github.com/users/jcfischer/repos","events_url":"https://api.github.com/users/jcfischer/events{/privacy}","received_events_url":"https://api.github.com/users/jcfischer/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":3,"created_at":"2013-12-16t14:14:50z","updated_at":"2013-12-17t13:23:52z","closed_at":"2013-12-17t13:23:52z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"### expected behaviour\r\nsyncing of diirectories with thumbnail or icon jpgs fails for many of the files\r\n\r\n### actual behaviour\r\nsync client reports \"problem: internal server error\" for most of the file synced\r\n\r\n### steps to reproduce\r\n1. sync directory\r\n\r\n### server configuration\r\noperating system: ubuntu 13.04\r\n\r\nweb server: apache 2.4\r\n\r\ndatabase: postgres 9.2\r\n\r\nphp version: 5.5\r\n\r\nowncloud version: 6.0.0a\r\n\r\nupdated from an older owncloud or fresh install: updated from 6.0rc4 (which had the same behaviour)\r\n\r\nlist of activated app: \r\n\r\nthe content of config/config.php: (without the database password and passwordsalt)\r\n\r\n````\r\n<?php\r\n$config = array (\r\n  'installed' => true,\r\n  'dbtype' => 'pgsql',\r\n  'dbname' => 'owncloud',\r\n  'dbuser' => 'owncloud',\r\n  'dbpassword' => 'xxx',\r\n  'dbhost' => '10.0.20.42',\r\n  'dbtableprefix' => 'oc_',\r\n  'passwordsalt' => 'xxx',\r\n  'forcessl' => false,\r\n  'blacklisted_files' =>\r\n  array (\r\n    0 => '.htaccess',\r\n  ),\r\n  'overwritehost' => '',\r\n  'overwriteprotocol' => '',\r\n  'overwritewebroot' => '',\r\n  'overwritecondaddr' => '',\r\n  'proxy' => '',\r\n  'proxyuserpwd' => '',\r\n  'theme' => '',\r\n  'default_language' => 'en',\r\n  '3rdpartyroot' => '',\r\n  '3rdpartyurl' => '',\r\n  'defaultapp' => 'files',\r\n  'knowledgebaseenabled' => true,\r\n  'appstoreenabled' => true,\r\n  'appstoreurl' => 'http://api.apps.owncloud.com/v1',\r\n  'mail_domain' => 'xxx.ch',\r\n  'mail_smtpdebug' => false,\r\n  'mail_smtpmode' => 'sendmail',\r\n  'mail_smtphost' => 'smtp.xxx.ch',\r\n  'mail_smtpport' => 25,\r\n  'mail_smtptimeout' => 10,\r\n  'mail_smtpsecure' => '',\r\n  'mail_smtpauth' => false,\r\n  'mail_smtpauthtype' => 'login',\r\n  'mail_smtpname' => '',\r\n  'mail_smtppassword' => '',\r\n  'trashbin_retention_obligation' => 30,\r\n  'allow_user_to_change_display_name' => false,\r\n  'appcodechecker' => '',\r\n  'updatechecker' => true,\r\n  'has_internet_connection' => true,\r\n  'check_for_working_webdav' => true,\r\n  'check_for_working_htaccess' => true,\r\n  'log_type' => 'owncloud',\r\n  'logfile' => '/var/log/owncloud/owncloud.log',\r\n  'loglevel' => '0',\r\n  'logdateformat' => 'f d, y h:i:s',\r\n  'logtimezone' => 'europe/berlin',\r\n  'log_query' => false,\r\n  'log_authfailip' => false,\r\n  'log_rotate_size' => 104857600,\r\n  'remember_login_cookie_lifetime' => 1296000,\r\n  'session_lifetime' => 86400,\r\n  'custom_csp_policy' => 'default-src \\'self\\'; script-src \\'self\\' \\'unsafe-eval\\'; style-src \\'self\\' \\'unsafe-inline\\'; frame-src *; img-src *; font-src \\'self\\' data:; media-src *',\r\n  'xframe_restriction' => true,\r\n  'datadirectory' => '/mnt/data',\r\n  'maintenance' => false,\r\n  'apps_paths' =>\r\n  array (\r\n    0 =>\r\n    array (\r\n      'path' => '/var/www/owncloud/apps',\r\n      'url' => '/apps',\r\n      'writable' => true,\r\n    ),\r\n  ),\r\n  'user_backends' =>\r\n  array (\r\n    0 =>\r\n    array (\r\n      'class' => 'oc_user_imap',\r\n      'arguments' =>\r\n      array (\r\n        0 => '{imap.gmail.com:993/imap/ssl}inbox',\r\n      ),\r\n    ),\r\n  ),\r\n  'customclient_desktop' => 'http://owncloud.org/sync-clients/',\r\n  'customclient_android' => 'https://play.google.com/store/apps/details?id=com.owncloud.android',\r\n  'customclient_ios' => 'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8',\r\n  'enable_previews' => true,\r\n  'preview_max_x' => null,\r\n  'preview_max_y' => null,\r\n  'preview_max_scale_factor' => 10,\r\n  'preview_libreoffice_path' => '/usr/bin/libreoffice',\r\n  'preview_office_cl_parameters' => '',\r\n  'enable_avatars' => true,\r\n  'openssl' =>\r\n  array (\r\n  ),\r\n  'instanceid' => 'oc94e94d8fd7',\r\n  'version' => '6.0.0.14',\r\n  'maxzipinputsize' => 838860800,\r\n  'allowzipdownload' => true,\r\n  'ldapignorenamingrules' => false,\r\n);\r\n````\r\n### client configuration\r\nbrowser: syncclient 1.4.2\r\n\r\noperating system: os x 10.8.5\r\n\r\n### logs\r\n#### web server error log\r\n```\r\nnone\r\n```\r\n\r\n#### syncclient log\r\n\r\n```\r\n14:23     reading/papers2/library.papers2/icons/8182ff7c-3778-4c61-905c-3734da4e64f9.jpg owncloud       problem: internal server error\r\n```\r\n\r\n#### owncloud log (data/owncloud.log)\r\nthe owncloud log does not show any entry for the file mentioned above, but has numeorus other problems.\r\n\r\non the other hand, files that have been uploaded correctly sometimes throw other errors:\r\n\r\n```\r\n{\"app\":\"oc\\\\files\\\\cache\\\\scanner\",\"message\":\"!!! path 'files\\/reading\\/papers2\\/library.papers2\\/thumbnails\\/f4de875e-4060-4650-a60f-7fc6bd33b135.jpg' is not readable !!!\",\"level\":0,\"time\":\"december 16, 2013 15:12:43\"}\r\n{\"app\":\"core\",\"message\":\"oc_image::loadfromfilehandle(): trying\",\"level\":0,\"time\":\"december 16, 2013 15:12:44\"}\r\n{\"app\":\"core\",\"message\":\"oc_image->fixorientation() no readable file path set.\",\"level\":0,\"time\":\"december 16, 2013 15:12:44\"}\r\n{\"app\":\"core\",\"message\":\"oc_image->fixorientation() orientation: -1\",\"level\":0,\"time\":\"december 16, 2013 15:12:44\"}\r\n{\"app\":\"hook\",\"message\":\"error while running hook (oca\\\\search_lucene\\\\hooks::indexfile): an exception occurred while executing 'insert into \\\"oc_jobs\\\"(\\\"class\\\", \\\"argument\\\", \\\"last_run\\\") values(?, ?, 0)':\\n\\nsqlstate[22001]: string data, right truncated: 7 error:  value too long for type character varying(256)\",\"level\":3,\"time\":\"december 16, 2013 15:12:44\"}\r\n```\r\n\r\n\r\n\r\n#### other information\r\n\r\nthe offending directory on the server has several hundred of partial files:\r\n\r\n```\r\n-rw-r--r-- 1 www-data www-data  24344 dec 16 13:22 placeholder_publication_400.jpg.part\r\n-rw-r--r-- 1 www-data www-data 164988 dec 16 13:22 e69f14de-14b3-493d-aee5-41e012309c6e.jpg.part\r\n-rw-r--r-- 1 www-data www-data  56084 dec 16 13:22 736a0eb6-bfe6-4397-8bb0-511002d70866.jpg.part\r\n-rw-r--r-- 1 www-data www-data 115800 dec 16 13:22 33b81fc7-4108-493d-9790-cc70d02b2d75.jpg.part\r\n```\r\n\r\n```\r\nroot@box-web1:/mnt/data/b1967ce2-f535-1032-8c41-d1ab18bc04c7/files/reading/papers2/library.papers2/thumbnails# ls -ltr | grep part | wc -l\r\n395\r\nroot@box-web1:/mnt/data/b1967ce2-f535-1032-8c41-d1ab18bc04c7/files/reading/papers2/library.papers2/thumbnails# ls -ltr | grep -v part | wc -l\r\n561\r\n```\r\n\r\nthe files are stored on an nfs server (and the two webservers that host owncloud both mount that directory)\r\n\r\nencryption of files is enabled\r\n\r\nuser authentication is done through ldap\r\n","closed_by":{"login":"jcfischer","id":3088,"avatar_url":"https://gravatar.com/avatar/5085ba37ba624a788e04a842cd09bd6e?d=https%3a%2f%2fidenticons.github.com%2fdc6a7e655d7e5840e66733e9ee67cc69.png&r=x","gravatar_id":"5085ba37ba624a788e04a842cd09bd6e","url":"https://api.github.com/users/jcfischer","html_url":"https://github.com/jcfischer","followers_url":"https://api.github.com/users/jcfischer/followers","following_url":"https://api.github.com/users/jcfischer/following{/other_user}","gists_url":"https://api.github.com/users/jcfischer/gists{/gist_id}","starred_url":"https://api.github.com/users/jcfischer/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jcfischer/subscriptions","organizations_url":"https://api.github.com/users/jcfischer/orgs","repos_url":"https://api.github.com/users/jcfischer/repos","events_url":"https://api.github.com/users/jcfischer/events{/privacy}","received_events_url":"https://api.github.com/users/jcfischer/received_events","type":"user","site_admin":false}}