{"url":"https://api.github.com/repos/owncloud/core/issues/5779","labels_url":"https://api.github.com/repos/owncloud/core/issues/5779/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/5779/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/5779/events","html_url":"https://github.com/owncloud/core/issues/5779","id":22354344,"number":5779,"title":"[oc6beta3] error with cloudian and sync client with directories","user":{"login":"ser72","id":5174383,"avatar_url":"https://gravatar.com/avatar/66c6eac865eac4d7a60f2a43800c4483?d=https%3a%2f%2fidenticons.github.com%2f927cc606da5dafe8d622924c22038100.png&r=x","gravatar_id":"66c6eac865eac4d7a60f2a43800c4483","url":"https://api.github.com/users/ser72","html_url":"https://github.com/ser72","followers_url":"https://api.github.com/users/ser72/followers","following_url":"https://api.github.com/users/ser72/following{/other_user}","gists_url":"https://api.github.com/users/ser72/gists{/gist_id}","starred_url":"https://api.github.com/users/ser72/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ser72/subscriptions","organizations_url":"https://api.github.com/users/ser72/orgs","repos_url":"https://api.github.com/users/ser72/repos","events_url":"https://api.github.com/users/ser72/events{/privacy}","received_events_url":"https://api.github.com/users/ser72/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/2+-+concept","name":"2 - concept","color":"ededed"},{"url":"https://api.github.com/repos/owncloud/core/labels/app%3afiles_external","name":"app:files_external","color":"02d7e1"},{"url":"https://api.github.com/repos/owncloud/core/labels/bug","name":"bug","color":"fc2929"}],"state":"open","assignee":null,"milestone":null,"comments":0,"created_at":"2013-11-08t18:23:11z","updated_at":"2013-11-13t11:22:25z","closed_at":null,"pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"**expected result**\r\ndirectories to be made and files to be synced\r\n\r\n**actual results**\r\ndirectories are made as files\r\nfiles not synced \r\n\r\n**steps**\r\nconfigure cloudian s3 server\r\nconfigure owncloud's external storage app pointing to that s3 server\r\ncreate a folder on the client with several folders in it\r\nhave several files in each folder\r\nsetup a sync from the client to the s3 directory on the server\r\n\r\nnotice the folders look like files on the server\r\nno files underneath are synced\r\n\r\noc logs:\r\n\r\n\r\n{\"app\":\"files_external\",\"message\":\"404 not found (request-id: b0fc5bf048a111e3)\",\"level\":3,\"time\":\"2013-11-08t18:15:05+00:00\"}\r\n{\"app\":\"files_external\",\"message\":\"404 not found (request-id: b18c3fe048a111e3)\",\"level\":3,\"time\":\"2013-11-08t18:15:06+00:00\"}\r\n\r\n\r\n\r\nfor each file\r\n\r\n\r\nclient logs\r\n\r\n1-08 13:03:47:378 check status.php from statusdialog. \r\n11-08 13:03:47:379 get request to   qurl( \"http://192.168.1.63/owncloud/status.php\" )  \r\n11-08 13:03:47:379 setting up host header:  \"192.168.1.63\" \r\n11-08 13:03:47:380 folder in overallstatus message:  mirall::folder(0x133ac90)  with name  \"sync4\" \r\n11-08 13:03:47:381 sync state changed for folder  \"sync4\" :  \"sync running\" \r\n11-08 13:03:44:364 csync_vio_stat: win32: stat-inode for c:\\users\\ser72\\desktop\\sync/1/file463.txt: 362811\r\n11-08 13:03:44:364 _csync_push_file: remote repository atomar push enabled for owncloud://192.168.1.63/owncloud/remote.php/webdav/amazons3/1/file463.txt (0).\r\n11-08 13:03:44:364 oc_module: => open called for owncloud://192.168.1.63/owncloud/remote.php/webdav/amazons3/1/file463.txt\r\n11-08 13:03:44:364 oc_module: stating directory owncloud://192.168.1.63/owncloud/remote.php/webdav/amazons3/1\r\n11-08 13:03:44:364 oc_module: owncloud_stat owncloud://192.168.1.63/owncloud/remote.php/webdav/amazons3/1 called\r\n11-08 13:03:44:364 oc_module: directory of file to open exists.\r\n11-08 13:03:44:364 oc_module: put request on /owncloud/remote.php/webdav/amazons3/1/file463.txt!\r\n11-08 13:03:44:364 oc_module: sendfile handling request type put. fd 3\r\n11-08 13:03:44:364 oc_module: about to send 1 block\r\n11-08 13:03:44:873 oc_module: chunk upload completed for 'owncloud://192.168.1.63/owncloud/remote.php/webdav/amazons3/1/file463.txt' (1024000 bytes out of 1024000)\r\n11-08 13:03:44:874 oc_module: chunk upload completed for 'owncloud://192.168.1.63/owncloud/remote.php/webdav/amazons3/1/file463.txt' (1024293 bytes out of 1024000)\r\n11-08 13:03:44:875 _csync_push_file: file: c:\\users\\ser72\\desktop\\sync/1/file463.txt, command: sendfile, error: invalid argument from errno 22\r\n11-08 13:03:44:875 _csync_push_file: remember chunk: 0  (transfer id -763523397 )\r\n11-08 13:03:44:875 _csync_report_parent_error: mark parent directoy `1` as an error\r\n1\r\n\r\nfor each file\r\n\r\n\r\n**note**\r\ncreating a folder directly on the web interface of owncloud works and creates the folder on the s3 server\r\n\r\n\r\n\r\n\r\n\r\n{\"installed\":\"true\",\"version\":\"6.0.0.5\",\"versionstring\":\"6.0 beta 3\",\"edition\":\"\"}\r\n\r\nubuntu\r\n\r\n\r\n","closed_by":null}