{"url":"https://api.github.com/repos/owncloud/core/issues/5149","labels_url":"https://api.github.com/repos/owncloud/core/issues/5149/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/5149/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/5149/events","html_url":"https://github.com/owncloud/core/issues/5149","id":20575794,"number":5149,"title":"\"yum update owncloud\" resets file owner","user":{"login":"lukeowncloud","id":2737900,"avatar_url":"https://gravatar.com/avatar/1ef1079dd415404dfaa9ebb3ff8d33a9?d=https%3a%2f%2fidenticons.github.com%2f3bfdcd91edc141c4b144458741032ea6.png&r=x","gravatar_id":"1ef1079dd415404dfaa9ebb3ff8d33a9","url":"https://api.github.com/users/lukeowncloud","html_url":"https://github.com/lukeowncloud","followers_url":"https://api.github.com/users/lukeowncloud/followers","following_url":"https://api.github.com/users/lukeowncloud/following{/other_user}","gists_url":"https://api.github.com/users/lukeowncloud/gists{/gist_id}","starred_url":"https://api.github.com/users/lukeowncloud/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lukeowncloud/subscriptions","organizations_url":"https://api.github.com/users/lukeowncloud/orgs","repos_url":"https://api.github.com/users/lukeowncloud/repos","events_url":"https://api.github.com/users/lukeowncloud/events{/privacy}","received_events_url":"https://api.github.com/users/lukeowncloud/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/packaging","name":"packaging","color":"593493"}],"state":"closed","assignee":null,"milestone":null,"comments":18,"created_at":"2013-10-06t06:20:17z","updated_at":"2013-12-19t16:50:28z","closed_at":"2013-12-19t16:49:19z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"### expected behaviour\r\nfor updating owncloud i login as root and type \"yum update owncloud\"\r\n\r\ni expect that after this command everythings works as neatly as before.\r\n\r\n### actual behaviour\r\nall (changed files, as it seems to me) files and the owncloud dir itself are owned by root:apache. result: 404 error on next request.\r\n\r\nfix: change files owner back to apache:apache\r\n\r\n### steps to reproduce\r\n1. yum update owncloud\r\n2. open owncloud/status.php --> 404\r\n\r\n### server configuration\r\noperating system:\r\ncentos release 6.3 \r\n\r\nweb server: \r\napache/2.2.15 \r\n\r\nowncloud version:\r\n5.0.11 --> 5.0.12\r\n","closed_by":{"login":"lukeowncloud","id":2737900,"avatar_url":"https://gravatar.com/avatar/1ef1079dd415404dfaa9ebb3ff8d33a9?d=https%3a%2f%2fidenticons.github.com%2f3bfdcd91edc141c4b144458741032ea6.png&r=x","gravatar_id":"1ef1079dd415404dfaa9ebb3ff8d33a9","url":"https://api.github.com/users/lukeowncloud","html_url":"https://github.com/lukeowncloud","followers_url":"https://api.github.com/users/lukeowncloud/followers","following_url":"https://api.github.com/users/lukeowncloud/following{/other_user}","gists_url":"https://api.github.com/users/lukeowncloud/gists{/gist_id}","starred_url":"https://api.github.com/users/lukeowncloud/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lukeowncloud/subscriptions","organizations_url":"https://api.github.com/users/lukeowncloud/orgs","repos_url":"https://api.github.com/users/lukeowncloud/repos","events_url":"https://api.github.com/users/lukeowncloud/events{/privacy}","received_events_url":"https://api.github.com/users/lukeowncloud/received_events","type":"user","site_admin":false}}