{"url":"https://api.github.com/repos/owncloud/core/issues/1219","labels_url":"https://api.github.com/repos/owncloud/core/issues/1219/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/1219/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/1219/events","html_url":"https://github.com/owncloud/core/issues/1219","id":10091039,"number":1219,"title":"owncloud fails silently when psotgresql server is unavailable","user":{"login":"arkascha","id":2156237,"avatar_url":"https://gravatar.com/avatar/9f792aed86f70eaed1b29e2f0398a881?d=https%3a%2f%2fidenticons.github.com%2fdb1707d51d6171a42a29fe8985cb531d.png&r=x","gravatar_id":"9f792aed86f70eaed1b29e2f0398a881","url":"https://api.github.com/users/arkascha","html_url":"https://github.com/arkascha","followers_url":"https://api.github.com/users/arkascha/followers","following_url":"https://api.github.com/users/arkascha/following{/other_user}","gists_url":"https://api.github.com/users/arkascha/gists{/gist_id}","starred_url":"https://api.github.com/users/arkascha/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/arkascha/subscriptions","organizations_url":"https://api.github.com/users/arkascha/orgs","repos_url":"https://api.github.com/users/arkascha/repos","events_url":"https://api.github.com/users/arkascha/events{/privacy}","received_events_url":"https://api.github.com/users/arkascha/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":9,"created_at":"2013-01-18t08:42:46z","updated_at":"2013-01-22t22:40:43z","closed_at":"2013-01-22t22:40:43z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"when owncloud is installed using a postgresql database server it fails silently when that server is not available. so after rebooting on a test environment for example. 'silently' here means: no error message at all, simply a blank page with no markup at all. \r\nthis obviously is a little inconvenient, since it does not exactly point towards the cause of the issue. ","closed_by":{"login":"mtgap","id":1097106,"avatar_url":"https://gravatar.com/avatar/454a73ee5feeb428d0c163a48903332c?d=https%3a%2f%2fidenticons.github.com%2f52d29a66f285a1d61125dd69ac0766b2.png&r=x","gravatar_id":"454a73ee5feeb428d0c163a48903332c","url":"https://api.github.com/users/mtgap","html_url":"https://github.com/mtgap","followers_url":"https://api.github.com/users/mtgap/followers","following_url":"https://api.github.com/users/mtgap/following{/other_user}","gists_url":"https://api.github.com/users/mtgap/gists{/gist_id}","starred_url":"https://api.github.com/users/mtgap/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mtgap/subscriptions","organizations_url":"https://api.github.com/users/mtgap/orgs","repos_url":"https://api.github.com/users/mtgap/repos","events_url":"https://api.github.com/users/mtgap/events{/privacy}","received_events_url":"https://api.github.com/users/mtgap/received_events","type":"user","site_admin":false}}