{"url":"https://api.github.com/repos/owncloud/core/issues/1910","labels_url":"https://api.github.com/repos/owncloud/core/issues/1910/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/1910/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/1910/events","html_url":"https://github.com/owncloud/core/issues/1910","id":11396549,"number":1910,"title":"upgrade to owncloud-4.5.6 failed with mysql error","user":{"login":"flacco","id":3701892,"avatar_url":"https://gravatar.com/avatar/524620c0c89fcdcb693301e713e3288c?d=https%3a%2f%2fidenticons.github.com%2f95db9d8e3e66d85fa2f7a4c614e8b732.png&r=x","gravatar_id":"524620c0c89fcdcb693301e713e3288c","url":"https://api.github.com/users/flacco","html_url":"https://github.com/flacco","followers_url":"https://api.github.com/users/flacco/followers","following_url":"https://api.github.com/users/flacco/following{/other_user}","gists_url":"https://api.github.com/users/flacco/gists{/gist_id}","starred_url":"https://api.github.com/users/flacco/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/flacco/subscriptions","organizations_url":"https://api.github.com/users/flacco/orgs","repos_url":"https://api.github.com/users/flacco/repos","events_url":"https://api.github.com/users/flacco/events{/privacy}","received_events_url":"https://api.github.com/users/flacco/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/duplicate","name":"duplicate","color":"cccccc"}],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2013-02-26t06:58:13z","updated_at":"2013-02-26t09:08:53z","closed_at":"2013-02-26t09:08:53z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"after the package upgrade, owncloud tries to upgrade the mysql database with the following sql-statement:\r\n\r\nalter table `locks` change `id` `id` int unsigned not null auto_increment primary key, change `timeout` `timeout` int unsigned default 0, change `created` `created` bigint default 0, change `scope` `scope` tinyint default 0, change `depth` `depth` tinyint default 0;\r\n\r\nthis fails because, mysql didn't accept to set a primary key in combination with the alter table command.\r\n\r\nerror: multiple primary key defined\r\n\r\nif i do it in the mysql shell it works without the \"primary key\" statement, but owncloud didn't recognize the db upgrade.\r\n\r\nstefan","closed_by":{"login":"raydiation","id":195053,"avatar_url":"https://gravatar.com/avatar/aa0d7b7302e0d7f4f9513c23b571383a?d=https%3a%2f%2fidenticons.github.com%2faf0a25e27510f77d97634a6bbe653b13.png&r=x","gravatar_id":"aa0d7b7302e0d7f4f9513c23b571383a","url":"https://api.github.com/users/raydiation","html_url":"https://github.com/raydiation","followers_url":"https://api.github.com/users/raydiation/followers","following_url":"https://api.github.com/users/raydiation/following{/other_user}","gists_url":"https://api.github.com/users/raydiation/gists{/gist_id}","starred_url":"https://api.github.com/users/raydiation/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/raydiation/subscriptions","organizations_url":"https://api.github.com/users/raydiation/orgs","repos_url":"https://api.github.com/users/raydiation/repos","events_url":"https://api.github.com/users/raydiation/events{/privacy}","received_events_url":"https://api.github.com/users/raydiation/received_events","type":"user","site_admin":false}}