{"url":"https://api.github.com/repos/owncloud/core/issues/2315","labels_url":"https://api.github.com/repos/owncloud/core/issues/2315/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/2315/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/2315/events","html_url":"https://github.com/owncloud/core/issues/2315","id":12024155,"number":2315,"title":"owncloud 5: after update to oc5 the shared folder disappeared","user":{"login":"dragotin","id":1070214,"avatar_url":"https://gravatar.com/avatar/af829234b31fb915704c1c65ef48eee0?d=https%3a%2f%2fidenticons.github.com%2f3392afab7f424e10623ba95a941f4d34.png&r=x","gravatar_id":"af829234b31fb915704c1c65ef48eee0","url":"https://api.github.com/users/dragotin","html_url":"https://github.com/dragotin","followers_url":"https://api.github.com/users/dragotin/followers","following_url":"https://api.github.com/users/dragotin/following{/other_user}","gists_url":"https://api.github.com/users/dragotin/gists{/gist_id}","starred_url":"https://api.github.com/users/dragotin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dragotin/subscriptions","organizations_url":"https://api.github.com/users/dragotin/orgs","repos_url":"https://api.github.com/users/dragotin/repos","events_url":"https://api.github.com/users/dragotin/events{/privacy}","received_events_url":"https://api.github.com/users/dragotin/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/bug","name":"bug","color":"fc2929"},{"url":"https://api.github.com/repos/owncloud/core/labels/sharing","name":"sharing","color":"e102d8"}],"state":"closed","assignee":null,"milestone":null,"comments":11,"created_at":"2013-03-14t15:41:57z","updated_at":"2013-04-07t20:08:11z","closed_at":"2013-04-07t20:08:11z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"after i  have updated from 4.5.7 to 5.0.0 from our packages. after the update, my user did not have a shared folder any more. after the user who has shared folders with me logged in once, my shared folder showed up again. \r\n\r\nat least one user reported the same to me.","closed_by":{"login":"mtgap","id":1097106,"avatar_url":"https://gravatar.com/avatar/454a73ee5feeb428d0c163a48903332c?d=https%3a%2f%2fidenticons.github.com%2f52d29a66f285a1d61125dd69ac0766b2.png&r=x","gravatar_id":"454a73ee5feeb428d0c163a48903332c","url":"https://api.github.com/users/mtgap","html_url":"https://github.com/mtgap","followers_url":"https://api.github.com/users/mtgap/followers","following_url":"https://api.github.com/users/mtgap/following{/other_user}","gists_url":"https://api.github.com/users/mtgap/gists{/gist_id}","starred_url":"https://api.github.com/users/mtgap/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mtgap/subscriptions","organizations_url":"https://api.github.com/users/mtgap/orgs","repos_url":"https://api.github.com/users/mtgap/repos","events_url":"https://api.github.com/users/mtgap/events{/privacy}","received_events_url":"https://api.github.com/users/mtgap/received_events","type":"user","site_admin":false}}